### **Pandas Series**
Pandas Series and it's operations

---

Pandas used for :
- Data Analysis
- Data Manipulation

---
Pandas has 2 objects :
- Series
- Dataframe

Series: 1-D array of data of any type. Just like a column in a table

In [1]:
# Importing Pandas
import numpy as np
import pandas as pd

### Initializing Series

In [2]:
# List of Strings values
country = ['India', 'Pakistan', 'USA', 'Nepal', 'Bangladesh']
pd.Series(country)

0         India
1      Pakistan
2           USA
3         Nepal
4    Bangladesh
dtype: str

- As you can see here, series contains **Index** and **Values**

In [3]:
# List of  Numeric values
runs = np.random.randint(1,100,5)
pd.Series(runs)

0    68
1    85
2    14
3    42
4    84
dtype: int32

In [4]:
# Custom Index
marks = np.random.randint(50,100,4)
subjects = ['Maths', 'English', 'Physics', 'Chemistry']

pd.Series(marks, index=subjects)

Maths        66
English      52
Physics      80
Chemistry    67
dtype: int32

In [5]:
# Naming a series
pd.Series(marks, index=subjects, name='Scorecard')

Maths        66
English      52
Physics      80
Chemistry    67
Name: Scorecard, dtype: int32

In [6]:
# Initializing series from dict
marks = {
    'Bio':87,
    'English':91,
    'Physics':50,
    'Chemistry':67
}

pd.Series(marks)

Bio          87
English      91
Physics      50
Chemistry    67
dtype: int64

In [7]:
# List of different data types
li = ['Lakshya',40,29,'Akshat',48]
pd.Series(li)

0    Lakshya
1         40
2         29
3     Akshat
4         48
dtype: object

- Here, object dtype means **string values** and int values are treated as strings

### Series Attributes

In [8]:
ms = pd.Series(marks, name='Scorecard')
ms

Bio          87
English      91
Physics      50
Chemistry    67
Name: Scorecard, dtype: int64

In [9]:
# size
ms.size # Number of elements in series

4

In [10]:
# dtype
ms.dtype # Type of element

dtype('int64')

In [11]:
# name
ms.name # Name of series

'Scorecard'

In [12]:
# is_unique
ms.is_unique # Tells if every item is unique or not

True

In [13]:
pd.Series([1,1,1,3,5,6,8,2]).is_unique

False

In [14]:
# index
ms.index # Gives index values

Index(['Bio', 'English', 'Physics', 'Chemistry'], dtype='str')

In [15]:
pd.Series([1,1,1,3,5,6,8,2]).index

RangeIndex(start=0, stop=8, step=1)

In [16]:
# values
ms.values # Gives values of series

array([87, 91, 50, 67])

### Initializing series from dataset

In [17]:
print(type(pd.read_csv('Pandas_Dataset\\subs.csv')))
pd.read_csv('Pandas_Dataset\\subs.csv') # Returns Dataframe

<class 'pandas.DataFrame'>

     Subscribers gained
0                    48
1                    57
2                    40
3                    43
4                    44
..                  ...
360                 231
361                 226
362                 155
363                 144
364                 172

[365 rows x 1 columns]

In [18]:
print(type(pd.read_csv('Pandas_Dataset\\subs.csv').squeeze()))
pd.read_csv('Pandas_Dataset\\subs.csv').squeeze()

<class 'pandas.Series'>

0       48
1       57
2       40
3       43
4       44
      ...
360    231
361    226
362    155
363    144
364    172
Name: Subscribers gained, Length: 365, dtype: int64

- Returns series in single column dataset
- Column name is taken as name automatically by pandas

In [19]:
# dataset with 2 columns
pd.read_csv('Pandas_Dataset\\kohli_ipl.csv')

     match_no  runs
0           1     1
1           2    23
2           3    13
3           4    12
4           5     1
..        ...   ...
210       211     0
211       212    20
212       213    73
213       214    25
214       215     7

[215 rows x 2 columns]

In [20]:
pd.read_csv('Pandas_Dataset\\kohli_ipl.csv', index_col='match_no').squeeze()

match_no
1       1
2      23
3      13
4      12
5       1
       ..
211     0
212    20
213    73
214    25
215     7
Name: runs, Length: 215, dtype: int64

In [21]:
pd.read_csv('Pandas_Dataset\\bollywood.csv')

                                     movie              lead
0                 Uri: The Surgical Strike     Vicky Kaushal
1                            Battalion 609       Vicky Ahuja
2     The Accidental Prime Minister (film)       Anupam Kher
3                          Why Cheat India     Emraan Hashmi
4                          Evening Shadows  Mona Ambegaonkar
...                                    ...               ...
1495                Hum Tumhare Hain Sanam    Shah Rukh Khan
1496                   Aankhen (2002 film)  Amitabh Bachchan
1497                       Saathiya (film)      Vivek Oberoi
1498                        Company (film)        Ajay Devgn
1499                  Awara Paagal Deewana      Akshay Kumar

[1500 rows x 2 columns]

In [22]:
pd.read_csv('Pandas_Dataset\\bollywood.csv', index_col='movie').squeeze()

movie
Uri: The Surgical Strike                   Vicky Kaushal
Battalion 609                                Vicky Ahuja
The Accidental Prime Minister (film)         Anupam Kher
Why Cheat India                            Emraan Hashmi
Evening Shadows                         Mona Ambegaonkar
                                              ...
Hum Tumhare Hain Sanam                    Shah Rukh Khan
Aankhen (2002 film)                     Amitabh Bachchan
Saathiya (film)                             Vivek Oberoi
Company (film)                                Ajay Devgn
Awara Paagal Deewana                        Akshay Kumar
Name: lead, Length: 1500, dtype: str

### Series Basic Methods

In [23]:
subs = pd.read_csv('Pandas_Dataset\\subs.csv').squeeze()
runs = pd.read_csv('Pandas_Dataset\\kohli_ipl.csv', index_col='match_no').squeeze()
lead = pd.read_csv('Pandas_Dataset\\bollywood.csv', index_col='movie').squeeze()

In [24]:
# head
subs.head() # Gives top 5 rows by default

0    48
1    57
2    40
3    43
4    44
Name: Subscribers gained, dtype: int64

In [25]:
subs.head(8)

0    48
1    57
2    40
3    43
4    44
5    46
6    33
7    40
Name: Subscribers gained, dtype: int64

In [26]:
# tail
subs.tail() # Gives last 5 rows by default

360    231
361    226
362    155
363    144
364    172
Name: Subscribers gained, dtype: int64

In [27]:
subs.tail(3)

362    155
363    144
364    172
Name: Subscribers gained, dtype: int64

In [28]:
# Sample
lead.sample() # Randomly gives row

movie
No Problem (2010 film)    Sanjay Dutt
Name: lead, dtype: str

In [29]:
lead.sample(3)

movie
Monica (film)    Ashutosh Rana
Madhoshi          Bipasha Basu
Dobara           Jackie Shroff
Name: lead, dtype: str

In [30]:
# value_counts
lead

movie
Uri: The Surgical Strike                   Vicky Kaushal
Battalion 609                                Vicky Ahuja
The Accidental Prime Minister (film)         Anupam Kher
Why Cheat India                            Emraan Hashmi
Evening Shadows                         Mona Ambegaonkar
                                              ...
Hum Tumhare Hain Sanam                    Shah Rukh Khan
Aankhen (2002 film)                     Amitabh Bachchan
Saathiya (film)                             Vivek Oberoi
Company (film)                                Ajay Devgn
Awara Paagal Deewana                        Akshay Kumar
Name: lead, Length: 1500, dtype: str

In [31]:
lead.value_counts() # Gives frequency of series values

lead
Akshay Kumar        48
Amitabh Bachchan    45
Ajay Devgn          38
Salman Khan         31
Sanjay Dutt         26
                    ..
Tanishaa Mukerji     1
Tanuja               1
Ankit                1
Rakhee Gulzar        1
Edwin Fernandes      1
Name: count, Length: 566, dtype: int64

In [32]:
# sort_values
runs

match_no
1       1
2      23
3      13
4      12
5       1
       ..
211     0
212    20
213    73
214    25
215     7
Name: runs, Length: 215, dtype: int64

In [33]:
runs.sort_values() # Sort values of series in ascending order

match_no
8        0
87       0
93       0
91       0
206      0
      ...
164    100
120    100
123    108
126    109
128    113
Name: runs, Length: 215, dtype: int64

In [34]:
runs.sort_values(ascending=False) # Sort values of series in descending order

match_no
128    113
126    109
123    108
120    100
164    100
      ...
93       0
130      0
206      0
207      0
211      0
Name: runs, Length: 215, dtype: int64

In [35]:
runs.sort_values(ascending=False).values[0]

np.int64(113)

In [36]:
runs.sort_values(inplace=True) # Made changes to original series, by default it's false
runs

match_no
8        0
87       0
93       0
91       0
206      0
      ...
164    100
120    100
123    108
126    109
128    113
Name: runs, Length: 215, dtype: int64

In [37]:
# sort_index
lead

movie
Uri: The Surgical Strike                   Vicky Kaushal
Battalion 609                                Vicky Ahuja
The Accidental Prime Minister (film)         Anupam Kher
Why Cheat India                            Emraan Hashmi
Evening Shadows                         Mona Ambegaonkar
                                              ...
Hum Tumhare Hain Sanam                    Shah Rukh Khan
Aankhen (2002 film)                     Amitabh Bachchan
Saathiya (film)                             Vivek Oberoi
Company (film)                                Ajay Devgn
Awara Paagal Deewana                        Akshay Kumar
Name: lead, Length: 1500, dtype: str

In [38]:
lead.sort_index() # Sort index of series

movie
1920 (film)                   Rajniesh Duggall
1920: London                     Sharman Joshi
1920: The Evil Returns             Vicky Ahuja
1971 (2007 film)                Manoj Bajpayee
2 States (2014 film)              Arjun Kapoor
                                   ...
Zindagi 50-50                      Veena Malik
Zindagi Na Milegi Dobara        Hrithik Roshan
Zindagi Tere Naam           Mithun Chakraborty
Zokkomon                       Darsheel Safary
Zor Lagaa Ke...Haiya!            Meghan Jadhav
Name: lead, Length: 1500, dtype: str

### Mathematical Methods on Series

In [39]:
subs = pd.read_csv('Pandas_Dataset\\subs.csv').squeeze()
runs = pd.read_csv('Pandas_Dataset\\kohli_ipl.csv', index_col='match_no').squeeze()
lead = pd.read_csv('Pandas_Dataset\\bollywood.csv', index_col='movie').squeeze()

In [42]:
# count
print(runs)
runs.count() # Gives total number of non missing values

match_no
1       1
2      23
3      13
4      12
5       1
       ..
211     0
212    20
213    73
214    25
215     7
Name: runs, Length: 215, dtype: int64

np.int64(215)

In [ ]:
# sum
print(subs)
subs.sum()

0       48
1       57
2       40
3       43
4       44
      ...
360    231
361    226
362    155
363    144
364    172
Name: Subscribers gained, Length: 365, dtype: int64

np.int64(49510)

In [76]:
# product
subs.prod() # 0 because of very huge number

np.int64(0)

In [74]:
subs.head(10).prod()

np.int64(40936751397273600)

In [59]:
# mean
subs.mean()

np.float64(135.64383561643837)

In [60]:
# median
runs.median()

np.float64(24.0)

In [61]:
# mode
lead.mode()

0    Akshay Kumar
Name: lead, dtype: str

In [62]:
# standard deviation
subs.std()

np.float64(62.6750230372527)

In [63]:
# variance
runs.var()

np.float64(688.0024777222343)

In [64]:
# min/max
print(subs.min())
print(subs.max())

33
396

In [75]:
# describe
runs.describe()

count    215.000000
mean      30.855814
std       26.229801
min        0.000000
25%        9.000000
50%       24.000000
75%       48.000000
max      113.000000
Name: runs, dtype: float64

### Indexing and Slicing

In [78]:
# Integer indexing
x = pd.Series(np.random.randint(1,100,10))
print(x)
x[4]

0    21
1    49
2     2
3    86
4    13
5    12
6    69
7    76
8    76
9    89
dtype: int32

np.int32(13)

In [80]:
x[-1] # Negative indexing don't work here

KeyError: -1

In [83]:
print(lead)
print(lead['Battalion 609'])
print(lead[1]) # This doesn't work here

movie
Uri: The Surgical Strike                   Vicky Kaushal
Battalion 609                                Vicky Ahuja
The Accidental Prime Minister (film)         Anupam Kher
Why Cheat India                            Emraan Hashmi
Evening Shadows                         Mona Ambegaonkar
                                              ...
Hum Tumhare Hain Sanam                    Shah Rukh Khan
Aankhen (2002 film)                     Amitabh Bachchan
Saathiya (film)                             Vivek Oberoi
Company (film)                                Ajay Devgn
Awara Paagal Deewana                        Akshay Kumar
Name: lead, Length: 1500, dtype: str
Vicky Ahuja

KeyError: 1

In [84]:
# Slicing
runs[5:11]

match_no
6      9
7     34
8      0
9     21
10     3
11    10
Name: runs, dtype: int64

In [86]:
runs[-5:] # Negative slicing works

match_no
211     0
212    20
213    73
214    25
215     7
Name: runs, dtype: int64

In [89]:
lead[-5:] # Integer slicing works on custom indices

movie
Hum Tumhare Hain Sanam      Shah Rukh Khan
Aankhen (2002 film)       Amitabh Bachchan
Saathiya (film)               Vivek Oberoi
Company (film)                  Ajay Devgn
Awara Paagal Deewana          Akshay Kumar
Name: lead, dtype: str

In [92]:
# Fancy Indexing
runs[[1,4,5,8]] # Any random index

match_no
1     1
4    12
5     1
8     0
Name: runs, dtype: int64

### Editing series

In [93]:
ms

Bio          87
English      91
Physics      50
Chemistry    67
Name: Scorecard, dtype: int64

In [98]:
# Using index
ms['English'] = 85 # Edits value of given index
ms

Bio          87
English      85
Physics      50
Chemistry    67
1            85
Maths        92
Name: Scorecard, dtype: int64

In [99]:
ms['Maths'] = 92 # Add new value if index not exist
ms

Bio          87
English      85
Physics      50
Chemistry    67
1            85
Maths        92
Name: Scorecard, dtype: int64

In [100]:
# Slicing
runs

match_no
1       1
2      23
3      13
4      12
5       1
       ..
211     0
212    20
213    73
214    25
215     7
Name: runs, Length: 215, dtype: int64

In [108]:
runs[2:5] = 100 # Actual index number works here
runs.head(8)

match_no
1     98
2     23
3    100
4    100
5    100
6      9
7     34
8      0
Name: runs, dtype: int64

In [109]:
# Fancy indexing
runs[[1,3,4]] = 98 # Custom index number works here
runs.head(8)

match_no
1     98
2     23
3     98
4     98
5    100
6      9
7     34
8      0
Name: runs, dtype: int64

### Series with Python functionality

In [115]:
# len/type/dir/sorted/max/min
print(len(subs))
print(type(subs))
print(dir(subs))
print(sorted(subs))
print(max(subs))
print(min(subs))

365
<class 'pandas.Series'>
['T', '_AXIS_LEN', '_AXIS_ORDERS', '_AXIS_TO_AXIS_NUMBER', '_HANDLED_TYPES', '__abs__', '__add__', '__and__', '__annotations__', '__array__', '__array_priority__', '__array_ufunc__', '__arrow_c_stream__', '__bool__', '__class__', '__contains__', '__copy__', '__deepcopy__', '__delattr__', '__delitem__', '__dict__', '__dir__', '__divmod__', '__doc__', '__eq__', '__finalize__', '__firstlineno__', '__floordiv__', '__format__', '__ge__', '__getattr__', '__getattribute__', '__getitem__', '__getstate__', '__gt__', '__hash__', '__iadd__', '__iand__', '__ifloordiv__', '__imod__', '__imul__', '__init__', '__init_subclass__', '__invert__', '__ior__', '__ipow__', '__isub__', '__iter__', '__itruediv__', '__ixor__', '__le__', '__len__', '__lt__', '__matmul__', '__mod__', '__module__', '__mul__', '__ne__', '__neg__', '__new__', '__or__', '__pandas_priority__', '__pos__', '__pow__', '__radd__', '__rand__', '__rdivmod__', '__reduce__', '__reduce_ex__', '__repr__', '__rfloordiv__', '__rmatmul__', '__rmod__', '__rmul__', '__ror__', '__round__', '__rpow__', '__rsub__', '__rtruediv__', '__rxor__', '__setattr__', '__setitem__', '__setstate__', '__sizeof__', '__static_attributes__', '__str__', '__sub__', '__subclasshook__', '__truediv__', '__weakref__', '__xor__', '_accessors', '_accum_func', '_agg_examples_doc', '_agg_see_also_doc', '_align_for_op', '_align_frame', '_align_series', '_append_internal', '_arith_method', '_attrs', '_binop', '_can_hold_na', '_check_copy_deprecation', '_check_inplace_and_allows_duplicate_labels', '_check_label_or_level_ambiguity', '_clip_with_one_bound', '_clip_with_scalar', '_cmp_method', '_consolidate', '_consolidate_inplace', '_construct_axes_dict', '_construct_result', '_constructor', '_constructor_expanddim', '_constructor_expanddim_from_mgr', '_constructor_from_mgr', '_dir_additions', '_dir_deletions', '_drop_axis', '_drop_labels_or_levels', '_duplicated', '_find_valid_index', '_flags', '_flex_method', '_from_mgr', '_get_axis', '_get_axis_name', '_get_axis_number', '_get_axis_resolvers', '_get_block_manager_axis', '_get_bool_data', '_get_cleaned_column_resolvers', '_get_index_resolvers', '_get_label_or_level_values', '_get_numeric_data', '_get_rows_with_mask', '_get_value', '_get_values_tuple', '_get_with', '_getitem_slice', '_gotitem', '_hidden_attrs', '_indexed_same', '_info_axis', '_info_axis_name', '_info_axis_number', '_init_dict', '_init_mgr', '_inplace_method', '_internal_names', '_internal_names_set', '_is_label_or_level_reference', '_is_label_reference', '_is_level_reference', '_is_mixed_type', '_ixs', '_logical_func', '_logical_method', '_map_values', '_memory_usage', '_metadata', '_mgr', '_min_count_stat_function', '_name', '_needs_reindex_multi', '_pad_or_backfill', '_reduce', '_references', '_reindex_axes', '_reindex_indexer', '_reindex_multi', '_reindex_with_indexers', '_rename', '_repr_data_resource_', '_repr_latex_', '_reset_cache', '_set_axis', '_set_axis_name', '_set_axis_nocheck', '_set_labels', '_set_name', '_set_value', '_set_values', '_set_with', '_set_with_engine', '_shift_with_freq', '_slice', '_stat_function', '_stat_function_ddof', '_to_latex_via_styler', '_typ', '_update_inplace', '_validate_dtype', '_values', '_where', 'abs', 'add', 'add_prefix', 'add_suffix', 'agg', 'aggregate', 'align', 'all', 'any', 'apply', 'argmax', 'argmin', 'argsort', 'array', 'asfreq', 'asof', 'astype', 'at', 'at_time', 'attrs', 'autocorr', 'axes', 'between', 'between_time', 'bfill', 'case_when', 'clip', 'combine', 'combine_first', 'compare', 'convert_dtypes', 'copy', 'corr', 'count', 'cov', 'cummax', 'cummin', 'cumprod', 'cumsum', 'describe', 'diff', 'div', 'divide', 'divmod', 'dot', 'drop', 'drop_duplicates', 'droplevel', 'dropna', 'dtype', 'dtypes', 'duplicated', 'empty', 'eq', 'equals', 'ewm', 'expanding', 'explode', 'factorize', 'ffill', 'fillna', 'filter', 'first_valid_index', 'flags', 'floordiv', 'from_arrow', 'ge', 'get', 'groupby', 'gt', 'hasnans', 'head', 'hist', 'iat', 'idxmax', 'idxmin', 'iloc', 'index', 'infer_objects', 'info', 'interpolate', 'is_monotonic_decreasing', 'is_monotonic_increasing', 'is_unique', 'isin', 'isna', 'isnull', 'item', 'items', 'keys', 'kurt', 'kurtosis', 'last_valid_index', 'le', 'list', 'loc', 'lt', 'map', 'mask', 'max', 'mean', 'median', 'memory_usage', 'min', 'mod', 'mode', 'mul', 'multiply', 'name', 'nbytes', 'ndim', 'ne', 'nlargest', 'notna', 'notnull', 'nsmallest', 'nunique', 'pct_change', 'pipe', 'plot', 'pop', 'pow', 'prod', 'product', 'quantile', 'radd', 'rank', 'rdiv', 'rdivmod', 'reindex', 'reindex_like', 'rename', 'rename_axis', 'reorder_levels', 'repeat', 'replace', 'resample', 'reset_index', 'rfloordiv', 'rmod', 'rmul', 'rolling', 'round', 'rpow', 'rsub', 'rtruediv', 'sample', 'searchsorted', 'sem', 'set_axis', 'set_flags', 'shape', 'shift', 'size', 'skew', 'sort_index', 'sort_values', 'squeeze', 'std', 'struct', 'sub', 'subtract', 'sum', 'swaplevel', 'tail', 'take', 'to_clipboard', 'to_csv', 'to_dict', 'to_excel', 'to_frame', 'to_hdf', 'to_json', 'to_latex', 'to_list', 'to_markdown', 'to_numpy', 'to_period', 'to_pickle', 'to_sql', 'to_string', 'to_timestamp', 'to_xarray', 'transform', 'transpose', 'truediv', 'truncate', 'tz_convert', 'tz_localize', 'unique', 'unstack', 'update', 'value_counts', 'values', 'var', 'where', 'xs']
[33, 33, 35, 37, 39, 40, 40, 40, 40, 42, 42, 43, 44, 44, 44, 45, 46, 46, 48, 49, 49, 49, 49, 50, 50, 50, 51, 54, 56, 56, 56, 56, 57, 61, 62, 64, 65, 65, 66, 66, 66, 66, 67, 68, 70, 70, 70, 71, 71, 72, 72, 72, 72, 72, 73, 74, 74, 75, 76, 76, 76, 76, 77, 77, 78, 78, 78, 79, 79, 80, 80, 80, 81, 81, 82, 82, 83, 83, 83, 84, 84, 84, 85, 86, 86, 86, 87, 87, 87, 87, 88, 88, 88, 88, 88, 89, 89, 89, 90, 90, 90, 90, 91, 92, 92, 92, 93, 93, 93, 93, 95, 95, 96, 96, 96, 96, 97, 97, 98, 98, 99, 99, 100, 100, 100, 101, 101, 101, 102, 102, 103, 103, 104, 104, 104, 105, 105, 105, 105, 105, 105, 105, 105, 105, 108, 108, 108, 108, 108, 108, 109, 109, 110, 110, 110, 111, 111, 112, 113, 113, 113, 114, 114, 114, 114, 115, 115, 115, 115, 117, 117, 117, 118, 118, 119, 119, 119, 119, 120, 122, 123, 123, 123, 123, 123, 124, 125, 126, 127, 128, 128, 129, 130, 131, 131, 132, 132, 134, 134, 134, 135, 135, 136, 136, 136, 137, 138, 138, 138, 139, 140, 144, 145, 146, 146, 146, 146, 147, 149, 150, 150, 150, 150, 151, 152, 152, 152, 153, 153, 153, 154, 154, 154, 155, 155, 156, 156, 156, 156, 157, 157, 157, 157, 158, 158, 159, 159, 160, 160, 160, 160, 162, 164, 166, 167, 167, 168, 170, 170, 170, 170, 171, 172, 172, 173, 173, 173, 174, 174, 175, 175, 176, 176, 177, 178, 179, 179, 180, 180, 180, 182, 183, 183, 183, 184, 184, 184, 185, 185, 185, 185, 186, 186, 186, 188, 189, 190, 190, 192, 192, 192, 196, 196, 196, 197, 197, 202, 202, 202, 203, 204, 206, 207, 209, 210, 210, 211, 212, 213, 214, 216, 219, 220, 221, 221, 222, 222, 224, 225, 225, 226, 227, 228, 229, 230, 231, 233, 236, 236, 237, 241, 243, 244, 245, 247, 249, 254, 254, 258, 259, 259, 261, 261, 265, 267, 268, 269, 276, 276, 290, 295, 301, 306, 312, 396]
396
33

In [118]:
# type conversion
print(ms)
list(ms)

Bio          87
English      85
Physics      50
Chemistry    67
1            85
Maths        92
Name: Scorecard, dtype: int64

[87, 85, 50, 67, 85, 92]

In [119]:
dict(ms)

{'Bio': np.int64(87),
 'English': np.int64(85),
 'Physics': np.int64(50),
 'Chemistry': np.int64(67),
 1: np.int64(85),
 'Maths': np.int64(92)}

In [121]:
# membership operator
print(lead)
'Why Cheat India' in lead

movie
Uri: The Surgical Strike                   Vicky Kaushal
Battalion 609                                Vicky Ahuja
The Accidental Prime Minister (film)         Anupam Kher
Why Cheat India                            Emraan Hashmi
Evening Shadows                         Mona Ambegaonkar
                                              ...
Hum Tumhare Hain Sanam                    Shah Rukh Khan
Aankhen (2002 film)                     Amitabh Bachchan
Saathiya (film)                             Vivek Oberoi
Company (film)                                Ajay Devgn
Awara Paagal Deewana                        Akshay Kumar
Name: lead, Length: 1500, dtype: str

True

In [124]:
print('Vicky Kaushal' in lead) # Works on index
print('Vicky Kaushal' in lead.values) # Works on values

False
True

In [ ]:
# looping
for i in lead:
    print(i) # Prints all the values

Vicky Kaushal
Vicky Ahuja
Anupam Kher
Emraan Hashmi
Mona Ambegaonkar
Geetika Vidya Ohlyan
Arshad Warsi
Radhika Apte
Kangana Ranaut
Nawazuddin Siddiqui
Ali Asgar
Ranveer Singh
Prit Kamani
Ajay Devgn
Sushant Singh Rajput
Amitabh Bachchan
Abhimanyu Dasani
Talha Arshad Reshi
Nawazuddin Siddiqui
Garima Agarwal
Rasika Agashe
Barun Sobti
Akshay Kumar
Zaheer Iqbal
Vidyut Jammwal
Deepika Amin
Manav Kaul
Naseeruddin Shah
Varun Dhawan
Shreyas Talpade
Tiger Shroff
Boman Irani
Ajay Devgn
Arjun Kapoor
Gavie Chahal
Prabhu Deva
Shahid Kapoor
Ayushmann Khurrana
Anupam Kher
Karanvir Bohra
Hrithik Roshan
Jimmy Sheirgill
John Abraham
Rishi Kapoor
Kangana Ranaut
Natalia Janoszek
Diljit Dosanjh
Sidharth Malhotra
Rajeev Khandelwal
Zaira Wasim
Akshay Kumar
Jacqueline Fernandez
Ayushmann Khurrana
Akshaye Khanna
Sonam Kapoor
Karan Deol
Sanjay Dutt
Bhavesh Kumar
Sanaya Irani
Ayushmann Khurrana
Siddhanth Kapoor
Akshay Kumar
Taapsee Pannu
Rajkummar Rao
Sunny Singh Nijjar
Neil Nitin Mukesh
Suraj Pancholi
Boman Irani
Riteish Deshmukh
Nawazuddin Siddiqui
Shahbaaz Khan
Kriti Kharbanda
Naseeruddin Shah
Vardhan Puri
Sushant Singh Rajput
Kartik Aaryan
Vidyut Jammwal
Rani Mukerji
Salman Khan
Akshay Kumar
Saif Ali Khan
Kay Kay Menon
Nora Fatehi
Ashmit Patel
Viineet Kumar
Rahul Bhat
Vicky Kaushal
Sidharth Malhotra
Deepika Padukone
Geetanjali Thapa
Akshay Anand
Pulkit Samrat
Kartik Aaryan
Lee Byford
Taapsee Pannu
Aisha Ahmed
Ajay Devgn
Rani Mukerji
Manoj Bajpayee
Tiger Shroff
Varun Dhawan
Prabhu Deva
Ishaan Khattar
Abhay Deol
Yogesh Raj Mishra
Rajkummar Rao
Alia Bhatt
Naseeruddin Shah
Sumeet Vyas
Vinay Pathak
John Abraham
Danny Denzongpa
Harshvardhan Kapoor
Jimmy Sheirgill
Anil Kapoor
Ishaan Khattar
Ranbir Kapoor
Sanjay Dutt
Dharmesh Yelande
Taapsee Pannu
Arjun Mathur
Irrfan Khan
Akshay Kumar
John Abraham
Sonakshi Sinha
Utkarsh Sharma
Dharmendra
Rajkummar Rao
Jackie Shroff
Avinash Tiwary
Manoj Bajpayee
Paoli Dam
Sanya Malhotra
Shahid Kapoor
Abhishek Bharate
Nawazuddin Siddiqui
Manish Anand
Taapsee Pannu
Jackky Bhagnani
Anushka Sharma
Radhika Apte
Rhea Chakraborty
Govinda
Sohum Shah
Kajol
Arjun Kapoor
Ayushmann Khurrana
Ayushmann Khurrana
Nargis Fakhri
Aishwarya Devan
Neil Nitin Mukesh
Shakti Kapoor
Amit Sadh
Sunny Deol
Rahul Bagga
Sunny Deol
Amyra Dastur
Shah Rukh Khan
Ranveer Singh
Salman Khan
Ajay Devgn
Varun Dhawan
Shraddha Kapoor
Sunil Grover
Hrithik Roshan
Raj Arjun
Aamir Khan
Gurmeet Ram Rahim Singh
Arsh Bajwa
Rana Daggubati
Naseeruddin Shah
Kangana Ranaut
Nana Patekar
Arbaaz Khan
Varun Dhawan
Rajkummar Rao
Govinda
Rajat Kapoor
Anushka Sharma
Kiara Advani
Shaurya Singh
Pankaj Tripathi
Taapsee Pannu
Adil Hussain
Amitabh Bachchan
Sunny Leone
Hema Malini
Raveena Tandon
Amitabh Bachchan
Amardeep Insan
Shraddha Kapoor
Ayushmann Khurrana
Sachin Tendulkar
Irrfan Khan
Himansh Kohli
Adil Hussain
Jayesh Raj
Manisha Koirala
Deepika Padukone
Rajkummar Rao
Salman Khan
Riteish Deshmukh
Shiv Darshan
Ranbir Kapoor
Ashish Bisht
Aahana Kumra
Manoj Babani
Rajveer Ankur Singh
Kirti Kulhari
Shah Rukh Khan
Tiger Shroff
Akshay Kumar
Anil Kapoor
Kartik Aaryan
Ayushmann Khurrana
Nawazuddin Siddiqui
Prisha Aneja
Aadar Jain
Ayushmann Khurrana
Kunal Kapoor
Arjun Rampal
Kangana Ranaut
Farhan Akhtar
Sidharth Malhotra
Hugh Bonneville
Rishi Kapoor
Rajkummar Rao
Kunaal Roy Kapur
Sunny Leone
Shraddha Kapoor
Rina Charaniya
Nawazuddin Siddiqui
Sunny Deol
Sridevi
Saif Ali Khan
Soundarya Sharma
Sudha Chandran
Manoj Bajpayee
Zaira Wasim
Prakash Belawadi
Kalki Koechlin
Rajkummar Rao
Richa Chadha
Irrfan Khan
Zareen Khan
Nayna Bandhopadhyay
Vidya Balan
Nishikant Kamat
Sanjay Mishra
Kapil Sharma
Pulkit Samrat
Vijay Varma
Sushama Deshpande
Richa Chadha
Prince Shah
Tanima Bhattacharya
Akshay Kumar
Zeenat Aman
Madhavan
Tusshar Kapoor
Tusshar Kapoor
Himansh Kohli
Sadhana Singh
Sunny Deol
Aditya Roy Kapoor
Rishi Kapoor
Rajniesh Duggall
Krishna Chaturvedi
Girish Taurani
Sonam Kapoor
Sukhesh Arora
Raima Sen
Anuj Sachdeva
Parthaa Akerkar
Priyanka Chopra
Sidharth Malhotra
John Abraham
Patralekhaa Paul
Shah Rukh Khan
Swara Bhaskar
Randeep Hooda
Shraddha Kapoor
Pankaj Tripathi
Jimmy Sheirgill
Kartik Elangovan
Boman Irani
Manoj Bajpayee
Sharman Joshi
Emraan Hashmi
Aanchal Dwivedi
Sanjay Singh
Arvind Swamy
Radhika Apte
Randeep Hooda
Sachiin Joshi
Kajal Aggarwal
Amitabh Bachchan
Shahid Kapoor
Hazel Croney
V. Ravichandran
Vipin Sharma
Nawazuddin Siddiqui
Pulkit Samrat
Tannishtha Chatterjee
Krrish Chhabria
Avinash Dhyani
Zeenat Aman
Salman Khan
Shashank Arora
Urvashi Rautela
Naseeruddin Shah
Sara Loren
Tom Alter
Irrfan Khan
John Abraham
Rajeev Khandelwal
Ileana D'Cruz
Sahil Anand
Hrithik Roshan
Diana Penty
Niharica Raizada
Tiger Shroff
Sidharth Malhotra
Nawazuddin Siddiqui
Emraan Hashmi
Taapsee Pannu
Tannishtha Chatterjee
Riteish Deshmukh
Yash Soni
Shreyas Talpade
Vinay Pathak
Jimmy Sharma
Sushant Singh Rajput
Ashok Insan
RJ Balaji
Saurav Chakraborty
Shashank Udapurkar
Shubham
Manoj Bajpayee
Sunny Leone
Aashish Bhatt
Ajay Devgn
Ronit Roy
Ranbir Kapoor
Neha Sharma
Farhan Akhtar
John Abraham
Alia Bhatt
Vaani Kapoor
Neha Dhupia
Jimmy Sheirgill
Sonarika Bhadoria
Amitabh Bachchan
Sharman Joshi
Aamir Khan
Harshvardhan Kapoor
Salman Khan
Kangana Ranaut
Kangana Ranaut
Soha Ali Khan
Prabhu Deva
Shah Rukh Khan
Salman Khan
Ranveer Singh
Anil Kapoor
Akshay Kumar
Akshay Kumar
Akshay Kumar
Akshay Kumar
Shakti Kapoor
Bipasha Basu
Arjun Kapoor
Zayed Khan
Malaika Arora
Naman Jain
Gurmeet Choudhary
Kay Kay Menon
Rati Agnihotri
Amitabh Bachchan
Arjun Rampal
Varun Dhawan
Swanand Kirkire
Sulabha Arya
Irrfan Khan
Nana Patekar
Ayushmann Khurrana
Anupam Kher
Gurmeet Ram Rahim Singh
Sidhant Gupta
Arjun Mathur
Ganesh Acharya
Anushka Sharma
Gulshan Devaiah
Sushant Singh Rajput
Adhyayan Suman
Vira Sathidar
Kalki Koechlin
Sunny Leone
Sara Loren
Emraan Hashmi
Auroshika Dey
Ira Dubey
Naseeruddin Shah
Vinay Pathak
Ram Kapoor
Deepika Padukone
Ranbir Kapoor
Shakti Anand
Anil Kapoor
Arshad Warsi
Meenakshi Dixit
Yash Acharya
Rajkummar Rao
Rahul Bagga
Mohit Baghel
Rishi Verma
Mimoh Chakraborty
Swara Bhaskar
Richa Chadha
Arshad Warsi
Mugdha Godse
Yashpal Sharma
Dharmendra
Sunny Deol
Smitha Gondkar
Kunal Kapoor
Ajay Devgn
Jacqueline Fernandez
Rishi Kapoor
Akshay Kumar
Vinay Pathak
Nawazuddin Siddiqui
Bhavita Anand
Saif Ali Khan
Suraj Pancholi
Shamim Khan
Irrfan Khan
Suhaas Ahuja
Jaideep Ahlawat
Charanpreet Insan
Akanksha Puri
Kunal Khemu
Aishwarya Rai Bachchan
Seema Azmi
Parveen Kaur
Kapil Sharma
Kartik Aaryan
Diganth
Shahid Kapoor
Nawazuddin Siddiqui
Kunal Khemu
Mann Bagga
Manish Paul
Sanjeev Kumar
Madhuri Dixit
Shiv Darshan
Gopi Desai
Mohinder Gujral
Zeenat Aman
Ranveer Singh
Salman Khan
Sidharth Malhotra
Adhyayan Suman
Indrapal Ahuja
Jimmy Sheirgill
Abhay Deol
Sahil Anand
Alia Bhatt
Sampat Pal Devi
Farhan Akhtar
Madhuri Dixit
Kangana Ranaut
Ayushmann Khurrana
Ali Zafar
Mahek Chahal
Monali Thakur
Sunny Leone
Harman Baweja
Sanjay Mishra
Sharman Joshi
Sachin Khedekar
Leeza Mangaldas
Pulkit Samrat
Zara Sheikh
Arjun Kapoor
Purab Kohli
Amitabh Bachchan
Varun Dhawan
Arvinder Bhatti
Kanika Batra
Jackky Bhagnani
Rajeev Khandelwal
Tanuj Virwani
Vijay Raaz
Kannan Arunachalam
Anjori Alagh
Satish Kaushik
Rahul Bagga
Himesh Reshammiya
Farooq Shaikh
Makrand Deshpande
Eesha Agarwal
Siddharth Gupta
Tiger Shroff
Rajkummar Rao
Sharib Hashmi
Kangana Ranaut
Kartik Aaryan
Swara Bhaskar
Simer Motiani
Anshuman Jha
Sidharth Malhotra
Vidya Balan
Saif Ali Khan
Varun Dhawan
Jay Bhanushali
Armaan Jain
Rajesh Khanna
Vir Das
Akshay Kumar
Jimmy Sheirgill
Reshmi Ghosh
Akshay Oberoi
Akshay Kumar
Anupam Kher
Rani Mukerji
Emraan Hashmi
Priyanka Chopra
Bipasha Basu
Deepika Padukone
Sonam Kapoor
Salil Acharya
Salman Khan
Saahil Prem
Alieesa P Badresia
Manoj Amarnani
Sasha Aagha
Tabu
Hrithik Roshan
Rati Agnihotri
Aditya Roy Kapoor
Asrani
Harshvardhan Deo
Nikhil Dwivedi
Karanvir Bohra
Puru Chibber
Soha Ali Khan
Rhea Chakraborty
Shah Rukh Khan
Rekha
Anupam Kher
Randeep Hooda
Akshay Kumar
Aadil Chahal
Shabana Azmi
Dimple Kapadia
Nishant Dahiya
Ranveer Singh
Emraan Hashmi
Saif Ali Khan
Vinod Acharya
Mannara Chopra
Prabhas
Mischa Barton
Shiv Panditt
Annu Kapoor
Barun Sobti
Rahul Bhat
Aamir Khan
Adhyayan Suman
Imran Khan
Naveen Kasturia
Arjun Rampal
Sarita Joshi
Kartik Aaryan
Juhi Chawla
Saif Ali Khan
Manisha Kelkar
Farooq Shaikh
Akshay Kumar
Randeep Hooda
Vivek Oberoi
Rajkummar Rao
Akash
Vishwa Mohan Badola
Neil Nitin Mukesh
Saqib Saleem
Arshad Warsi
Jimmy Sheirgill
Asha Bhosle
Kamal Haasan
Jackky Bhagnani
Aditya Roy Kapoor
Emraan Hashmi
Ajay Devgn
Ayushmann Khurrana
Vivek Oberoi
Vidyut Jammwal
Rani Mukerji
Saif Ali Khan
Riya Vij
Arjun Kapoor
Preity Zinta
Veena Malik
Ranbir Kapoor
Pulkit Samrat
Rupa Bhimani
Dhanush
Kay Kay Menon
Neil Nitin Mukesh
Vidya Balan
Anupam Kher
Sanjay Dutt
Farhan Akhtar
Wamiqa Gabbi
Shadab Kamal
Sunil Shetty
Prateik
Tusshar Kapoor
Tanuj Virwani
Poonam Pandey
Deepak Dobriyal
Hemant Gopal
Joy Mukherjee
Rishi Kapoor
Rajesh Tailang
Akshay Kumar
John Abraham
Amitabh Bachchan
Sushant Singh Rajput
Shruti Haasan
Deepika Padukone
Vivek Oberoi
Naseeruddin Shah
Karan Kundrra
Shahid Kapoor
Aida Elkashef
Irrfan Khan
Anisa Butt
Akshay Kumar
Rajkummar Rao
Manish Paul
Puneet Singh Ratn
Kangana Ranaut
Sumit Nijhawan
Tinnu Anand
Chandan Roy Sanyal
Elisha Kriis
Ashmit Patel
Imran Khan
Manu Rishi Chadha
Naseeruddin Shah
Paresh Rawal
Saif Ali Khan
Aamir Khan
Ali Zafar
Ranveer Singh
Sharman Joshi
Naseeruddin Shah
Shiney Ahuja
Karan Sharma
Sunny Deol
Ranveer Singh
Hrithik Roshan
Kareena Kapoor
Prateik
Kiran Bhatia
Bipasha Basu
Riteish Deshmukh
Jahangir Khan
Irrfan Khan
Vidya Balan
Mithun Chakraborty
Kareena Kapoor
Manish Chaudhary
Kavin Dave
Shikhi Gupta
Archana Joglekar
Tusshar Kapoor
Pulkit Samrat
Ayushmann Khurrana
Nikhil Dwivedi
Anil Kapoor
Karisma Kapoor
Arjun Kapoor
Sanjay Dutt
Gul Panag
Yudhveer Bakoliya
Kay Kay Menon
Emraan Hashmi
Sharman Joshi
Shahid Kapoor
Anupam Kher
Anya Anand
Julia Datt
Manoj Bajpayee
Manoj Bajpayee
Saif Ali Khan
Naresh Sharma
Riteish Deshmukh
Sonu Sood
Nassar Abdulla
Salman Khan
Vickrant Mahajan
Freny Bhagat
Akshay Kumar
Omkar Das Manikpuri
Sunil Shetty
Manoj Bajpayee
Bidita Bag
Harish Chabbra
Ranbir Kapoor
Kareena Kapoor
Sagar Bhangade
Vivek Oberoi
Ravi Kishan
Paresh Rawal
Rani Mukerji
Manoj Bajpayee
J.D. Chakravarthi
Cary Elwes
Arjun Rampal
Alia Bhatt
Jackky Bhagnani
Emraan Hashmi
Vicky Ahuja
Sunidhi Chauhan
Asrani
Shah Rukh Khan
Aamir Khan
Himanshu Bhatt
Ajay Devgn
Ashok Banthia
Salman Khan
Vinod Khanna
Akshay Kumar
Amitabh Bachchan
Sridevi
Vivek Sudershan
Nafisa Ali
Mohsin
Prateik
Gul Panag
Vatsal Sheth
Ajay Devgn
Russell Geoffrey Banks
Vinay Pathak
Rishi Kapoor
Priyanka Chopra
Madhavan
Arshad Warsi
Deepti Naval
Akshay Kumar
Sumit Arora
Anay
Om Puri
Abhishek Bachchan
Sendhil Ramamurthy
Darsheel Safary
Vinay Pathak
Ishaan Manhaas
Sanjay Mishra
Ashutosh Rana
Juhi Chawla
Govinda
Mimoh Chakraborty
Tusshar Kapoor
Kainaz Motivala
Partho A. Gupte
Nana Patekar
Sara Arjun
Kalki Koechlin
Kartik Aaryan
Vinay Pathak
Lillete Dubey
Sanjay Dutt
Amitabh Bachchan
Imran Khan
Emraan Hashmi
Aarav Khanna
Hrithik Roshan
Raghuvir Yadav
Gulshan Grover
Naushaad Abbas
Shefali Shah
Ajay Devgn
Rahul Jaiswal
Apoorva Arora
Isha Koppikar
Rajniesh Duggall
Amitabh Bachchan
Sanjay Dutt
Anupam Kher
Salman Khan
Deepshika Nagpal
Deepak Dobriyal
Tusshar Kapoor
Kiron Kher
Imran Khan
Shahid Kapoor
Mikaal
John Abraham
Jimmy Sheirgill
Vinay Pathak
Vinay Virmani
Dev Anand
Zayed Khan
Saqib Saleem
Sachiin Joshi
Shah Rukh Khan
Ranbir Kapoor
Chirag Paswan
Dharmendra
Himesh Reshammiya
Ranveer Singh
Akshay Kumar
Abhishek Bachchan
Rani Mukerji
Ajay Devgn
Vidya Balan
Priyanka Chopra
Shahid Kapoor
Prateik
Salman Khan
Siddharth
Amitabh Bachchan
Vidya Balan
Paresh Rawal
Sunny Gill
Shreyas Talpade
Tabu
Shah Rukh Khan
Amitabh Bachchan
Siddhartha Gupta
Shah Rukh Khan
Tanushree Dutta
Paul Sidhu
Sunny Deol
Gurdas Maan
Master Shams
Om Puri
Vikrum Kumar
Aditya Narayan
Arshad Warsi
Boman Irani
Nana Patekar
Priyanka Chopra
Arbaaz Khan
Rekha
Rahul Bose
Nana Patekar
Sudeep
Farooq Shaikh
Rohit Roy
Sachin Khedekar
Anuj Saxena
Akshay Kumar
Hazel Croney
Sanjeev Bhaskar
Vivek Oberoi
Abhishek Bachchan
Atul Kulkarni
Rajpal Yadav
Hrithik Roshan
Nushrat Bharucha
Kareena Kapoor
Bhushan Agarwal
Prashant Narayanan
Sanjay Dutt
Akshay Kumar
Ali Zafar
Rajat Barmecha
Ajay Devgn
Bobby Deol
Omkar Das Manikpuri
Neil Nitin Mukesh
Gul Panag
Raj Singh Chaudhary
John Abraham
Barkha Madan
Salman Khan
Supriya Pathak
Sunil Shetty
Rituparna Sengupta
Ranvir Shorey
Mallika Sherawat
Emraan Hashmi
Rishi Kapoor
Ajay Devgn
Manoj Bajpayee
Sanjay Dutt
John Abraham
Hrithik Roshan
Varun Bhagwat
Deepika Padukone
Sunny Deol
Rajat Kapoor
Akanksha
Jimmy Sheirgill
Sanjay Dutt
Ranveer Singh
Aditya Srivastava
Arunoday Singh
Akshay Kumar
Akshay Oberoi
Ajay Devgn
Neil Nitin Mukesh
Sahil Khan
Imran Khan
Sushmita Sen
Priyanka Chopra
Zeenat Aman
Bipasha Basu
Akshay Kumar
Aamir Khan
Farhan Akhtar
Saif Ali Khan
Salman Khan
Waheeda Rehman
Kangana Ranaut
Hrishitaa Bhatt
Ranbir Kapoor
Asrani
Irrfan Khan
Kay Kay Menon
Arshad Warsi
Paresh Rawal
Rati Agnihotri
Harman Baweja
Shahid Kapoor
Fardeen Khan
John Abraham
Kay Kay Menon
Aftab Shivdasani
Naseeruddin Shah
Inaamulhaq
Neil Nitin Mukesh
Kunal Khemu
Bobby Deol
Anita
Parzaan Dastur
Meghan Jadhav
Shreyas Talpade
John Abraham
Kay Kay Menon
Sanjay Dutt
Mithun Chakraborty
Govinda
Sunil Shetty
Jackie Shroff
Anupam Kher
Shreyas Talpade
Rishi Kapoor
Rajendra Prasad
Arjun Rampal
Mithun Chakraborty
Mithun Chakraborty
Bobby Deol
Shahid Kapoor
Harman Baweja
Fardeen Khan
Sanjay Dutt
Ranbir Kapoor
Salman Khan
Akshay Kumar
Atmaram Bhende
Amitabh Bachchan
Salman Khan
Manoj Bajpayee
Emraan Hashmi
Lewis Tan
Akshay Kumar
Amitabh Bachchan
Ranbir Kapoor
Aamir Bashir
Farooq Shaikh
Mithun Chakraborty
Abhishek Bachchan
Saif Ali Khan
Shah Rukh Khan
Aamir Khan
Akshay Kumar
Ajay Devgn
Hrithik Roshan
Ranbir Kapoor
Amitabh Bachchan
Amitabh Bachchan
Ajay Devgn
Omkar Bhatkar
Shreyas Talpade
Manisha Koirala
Ajay Devgn
Tusshar Kapoor
Juhi Chawla
Ajay Devgn
Kay Kay Menon
Akshay Kumar
Dino Morea
Mimoh Chakraborty
Emraan Hashmi
Mithun Chakraborty
Sikander Kher
Paresh Rawal
Ahraz Ahmed
Aftab Shivdasani
Amita Pathak
Saahil Chadha
Saif Ali Khan
Kay Kay Menon
Shahid Kapoor
Harman Baweja
Adhvik Mahajan
Vivek Oberoi
Govinda
Amitabh Bachchan
Paresh Rawal
Mallika Sherawat
Arjun Rampal
Tusshar Kapoor
Bobby Deol
Sammir Dattani
Victor Banerjee
Rajniesh Duggall
Amitabh Bachchan
Shreyas Talpade
Kiron Kher
Jackie Shroff
Jayshree Arora
Sharman Joshi
Himesh Reshammiya
Sohail Khan
Saif Ali Khan
Isha Koppikar
Kamal Rashid Khan
Priyanka Chopra
Vinay Pathak
Salman Khan
Abhay Deol
Vinay Pathak
Shabana Azmi
Manoj Bajpayee
Anupam Kher
Rajesh Khanna
Dino Morea
Irrfan Khan
Amitabh Bachchan
Himesh Reshammiya
Tusshar Kapoor
Nauheed Cyrusi
Madhuri Dixit
Dharmendra
Emraan Hashmi
Vinay Pathak
Akshay Kumar
Dino Morea
Sunny Deol
Mouli Ganguly
Krishna Abhishek
Irrfan Khan
Kay Kay Menon
Pankaj Kapur
Jazzy Doe
Mona Ambegaonkar
Ajay Devgn
Amitabh Bachchan
Jimmy Sheirgill
Fardeen Khan
Shah Rukh Khan
Sanjay Dutt
John Abraham
Pankaj Kapur
Sunil Pal
Muzamil Ibrahim
Imaaduddin Shah
Sharman Joshi
Abhay Deol
Arjun Rampal
Akshaye Khanna
Rishi Kapoor
Arbaaz Khan
Amitabh Bachchan
Gautam Gupta
Mohan Azaad
Juanna Sanghvi
Mithun Chakraborty
Ranvir Shorey
Govinda
Abhishek Bachchan
Shahid Kapoor
Tusshar Kapoor
Shahid Kapoor
Shiney Ahuja
Dharmendra
Fardeen Khan
Tusshar Kapoor
Rekha
Jimmy Sheirgill
Rani Mukerji
Dharmendra
Shabana Azmi
Abhay Deol
Salman Khan
Menekka Arora
Nana Patekar
Bobby Deol
Linda Arsenio
Kal Penn
Akshay Kumar
Jason Lewis
Sanjay Dutt
Amitabh Bachchan
John Abraham
Shah Rukh Khan
Salman Khan
Rahul Khanna
Dwij Yadav
Aftab Shivdasani
Vinod Khanna
Bobby Deol
Sherlyn Chopra
Salman Khan
Rani Mukerji
Mahima Chaudhry
Mandar Jadhav
Aftab Shivdasani
Amitabh Bachchan
Jimmy Sheirgill
Manoj Bajpayee
Darsheel Safary
Saif Ali Khan
Urmila Matondkar
Kunal Khemu
Emraan Hashmi
Tushar Jalota
Jaya Bachchan
Akshay Kumar
Akshaye Khanna
Jeetendra
Akshaye Khanna
Abhay Deol
Emraan Hashmi
Akshay Kapoor
Sanjay Dutt
Bobby Darling
Aftab Shivdasani
Rekha
Amitabh Bachchan
Rati Agnihotri
Rahul Dev
Naseeruddin Shah
Urmila Matondkar
Juhi Chawla
Akshay Kumar
Sushmita Sen
Jackie Shroff
Somesh Agarwal
Sohail Khan
Kareena Kapoor
Bipasha Basu
Amitabh Bachchan
Rajit Kapoor
Emraan Hashmi
Ishrat Ali
Raj Tara
Hrithik Roshan
Ayesha Takia
Shah Rukh Khan
Amitabh Bachchan
Aamir Khan
Kangana Ranaut
Ajay Devgn
Ram Kapoor
Sunil Shetty
Ajay Devgn
Akshay Kumar
Arjun Rampal
Arjun Rampal
Aftab Shivdasani
Salman Khan
Emraan Hashmi
Onjolee Nair
Amarjeet
Anupam Kher
Amitabh Bachchan
Rishi Kapoor
Sanjay Dutt
John Abraham
Nassar Abdulla
Rekha
Paresh Rawal
Ajay Devgn
Rahul Bose
Sunny Deol
Akshay Kumar
Fardeen Khan
Akshay Kumar
Jeetendra
Sarika
Aamir Khan
Salman Khan
Govinda
Akshaye Khanna
Salman Khan
Mohit Ahlawat
Mahima Chaudhry
Ajay Devgn
Mohammad Amir Naji
Sanjay Dutt
Irrfan Khan
Aishwarya Rai Bachchan
Nana Patekar
Sunny Deol
Shahid Kapoor
Priyanshu Chatterjee
Gurdas Maan
Kangana Ranaut
Paresh Rawal
Jimmy Sheirgill
Sushmita Sen
Rakesh Bedi
Emraan Hashmi
Manisha Koirala
Ajay Devgn
Rekha
Juhi Chawla
Bobby Deol
Anil Kapoor
Amitabh Bachchan
Sanjay Dutt
Abhishek Bachchan
Shawar Ali
Ali Asgar
Tabu
Ajay Devgn
Abhishek Bachchan
Aryan Vaid
Jatin Grewal
Samir Aftab
Anil Kapoor
Randeep Hooda
Akshay Kumar
Saayli Buva
Bipasha Basu
Amitabh Bachchan
Akshay Kumar
Mithun Chakraborty
Sanjay Dutt
Arjun Rampal
Shilpa Shetty Kundra
Amitabh Bachchan
Siddharth Koirala
Fardeen Khan
Ayesha Jhulka
Aseel Adel
Vivek Oberoi
Akshay Kumar
Shreyas Talpade
Chiranjeevi
Kay Kay Menon
Akshay Kumar
Sunny Deol
John Abraham
Ajay Devgn
Kunal Khemu
Lucky Ali
Mukesh Khanna
Mohit Ahlawat
Vivek Oberoi
Aftab Shivdasani
Shilpa Shetty Kundra
Kamal Adib
Arshad Warsi
Tusshar Kapoor
Salman Khan
Ajay Devgn
Salman Khan
Rajpal Yadav
Anupam Kher
Salman Khan
Aamir Khan
Dia Mirza
Dev Anand
Sanjay Suri
Anil Kapoor
Urmila Matondkar
Uday Chopra
Anil Kapoor
Sunil Shetty
Konkona Sen Sharma
Shabana Azmi
Saif Ali Khan
Vinod Khanna
Shah Rukh Khan
Irrfan Khan
Rishi Kapoor
Saif Ali Khan
Kashmira Shah
Amitabh Bachchan
Arshad Warsi
Sanjay Dutt
Ashutosh Rana
Neha Dhupia
Madhavan
Tabu
Abhay Deol
Zulfi Sayed
Ajay Devgn
Nassar Abdulla
Arjun Rampal
Shahid Kapoor
Aarti Chhabria
Fardeen Khan
Amitabh Bachchan
Amitabh Bachchan
Vikram Aditya
Arjun Rampal
Emraan Hashmi
Shah Rukh Khan
Shah Rukh Khan
Ajay Devgn
Salman Khan
Abhishek Bachchan
Amitabh Bachchan
Saif Ali Khan
Akshaye Khanna
Mallika Sherawat
Ajay Devgn
Akshay Kumar
Amitabh Bachchan
Amitabh Bachchan
Shatrughan Sinha
Bobby Deol
Kareena Kapoor
Jimmy Sheirgill
Arjun Rampal
Jimmy Sheirgill
Amitabh Bachchan
Amitabh Bachchan
Shahid Kapoor
Salman Khan
Jackie Shroff
Naveen Bawa
Vikaas Kalantari
Tusshar Kapoor
Kareena Kapoor
Salman Khan
Sunil Shetty
Saif Ali Khan
Isha Koppikar
Akshay Kumar
Aniket Vishwasrao
Shawar Ali
Tisca Chopra
Neha Dhupia
Raqesh Bapat
Manoj Bajpayee
Mallika Sherawat
Dino Morea
Sohail Khan
Kiron Kher
Bobby Deol
Sunny Deol
Sohail Khan
Amitabh Bachchan
Bipasha Basu
Hrithik Roshan
Dino Morea
Irrfan Khan
Aftab Shivdasani
Tabu
Anil Kapoor
Prithviraj Kapoor
Aftab Shivdasani
Akshay Kumar
Antara Mali
Vinay Anand
John Abraham
Salman Khan
Sanjay Dutt
Akshay Kumar
Manisha Koirala
Akshay Kapoor
Sanjay Dutt
Ajay Devgn
Sanjay Dutt
Sanjay Suri
Abhishek Bachchan
Sunny Deol
Aftab Shivdasani
Shah Rukh Khan
Vatsal Sheth
Madhavan
Tusshar Kapoor
Emraan Hashmi
Vicky Ahuja
Shah Rukh Khan
Tarun Arora
Diwakar Pathak
Arya Babbar
Rekha
Shah Rukh Khan
Anupam Kher
Shah Rukh Khan
Sunny Deol
Amitabh Bachchan
Hrithik Roshan
Sanjay Dutt
Sanjay Dutt
Sanjay Dutt
Ajay Devgn
Atul Kulkarni
Naseeruddin Shah
Arun Bakshi
Priyanshu Chatterjee
Ajay Devgn
Amitabh Bachchan
Sudesh Berry
Akshay Kumar
Akshay Kumar
Amitabh Bachchan
Ajay Devgn
Anil Kapoor
Jackie Shroff
Sadashiv Amrapurkar
Sooraj Balaji
Arjun Rampal
Sameera Reddy
Om Puri
Amar Upadhyaya
Zayed Khan
Nawazuddin Siddiqui
Vivek Oberoi
Kapil Jhaveri
Nandita Das
Aftab Shivdasani
Manisha Koirala
Rahul Bose
Ajay Devgn
Tabu
Jimmy Sheirgill
Sanjay Dutt
Akshaye Khanna
Vikram Dasu
Reef Karim
Jaz Pandher
Rushali Arora
Ashmit Patel
Sunny Deol

In [128]:
for i in lead.index:
    print(i) # Print all indices

Uri: The Surgical Strike
Battalion 609
The Accidental Prime Minister (film)
Why Cheat India
Evening Shadows
Soni (film)
Fraud Saiyaan
Bombairiya
Manikarnika: The Queen of Jhansi
Thackeray (film)
Amavas
Gully Boy
Hum Chaar
Total Dhamaal
Sonchiriya
Badla (2019 film)
Mard Ko Dard Nahi Hota
Hamid (film)
Photograph (film)
Risknamaa
Mere Pyare Prime Minister
22 Yards
Kesari (film)
Notebook (2019 film)
Junglee (2019 film)
Gone Kesh
Albert Pinto Ko Gussa Kyun Aata Hai?
The Tashkent Files
Kalank
Setters (film)
Student of the Year 2
PM Narendra Modi
De De Pyaar De
India's Most Wanted (film)
Yeh Hai India
Khamoshi (2019 film)
Kabir Singh
Article 15 (film)
One Day: Justice Delivered
Hume Tumse Pyaar Kitna
Super 30 (film)
Family of Thakurganj
Batla House
Jhootha Kahin Ka
Judgementall Hai Kya
Chicken Curry Law
Arjun Patiala
Jabariya Jodi
Pranaam
The Sky Is Pink
Mission Mangal
Saaho
Dream Girl (2019 film)
Section 375
The Zoya Factor (film)
Pal Pal Dil Ke Paas
Prassthanam
P Se Pyaar F Se Faraar
Ghost (2019 film)
Bala (2019 film)
Yaaram (2019 film)
Housefull 4
Saand Ki Aankh
Made in China (2019 film)
Ujda Chaman
Bypass Road (film)
Satellite Shankar
Jhalki
Marjaavaan
Motichoor Chaknachoor
Keep Safe Distance (film)
Pagalpanti (2019 film)
Ramprasad Ki Tehrvi
Yeh Saali Aashiqui
Dil Bechara
Pati Patni Aur Woh (2019 film)
Commando 3 (film)
Mardaani 2
Dabangg 3
Good Newwz
Kaalakaandi
Vodka Diaries
My Birthday Song
Nirdosh
Mukkabaaz
Union Leader (film)
Love per Square Foot
Aiyaary
Padmaavat
Kuchh Bheege Alfaaz
Jaane Kyun De Yaaron
Veerey Ki Wedding
Sonu Ke Titu Ki Sweety
Hate Story 4
Dil Juunglee
3 Storeys
Raid (2018 film)
Hichki
Missing (2018 film)
Baaghi 2
October (2018 film)
Mercury (film)
Beyond the Clouds (2017 film)
Nanu Ki Jaanu
Daas Dev
Omerta (film)
Raazi
Hope Aur Hum
High Jack (film)
Khajoor Pe Atke
Parmanu: The Story of Pokhran
Bioscopewala
Bhavesh Joshi Superhero
Phamous
Race 3
Dhadak
Sanju
Saheb Biwi Aur Gangster 3
Nawabzaade
Mulk (film)
Brij Mohan Amar Rahe
Karwaan
Gold (2018 film)
Satyameva Jayate (2018 film)
Happy Phirr Bhag Jayegi
Genius (2018 Hindi film)
Yamla Pagla Deewana: Phir Se
Stree (2018 film)
Paltan (film)
Laila Majnu (2018 film)
Gali Guleiyan
Halkaa
Pataakha
Batti Gul Meter Chalu
Love Sonia
Manto (2018 film)
Ishqeria
Manmarziyaan
Mitron
Sui Dhaaga
Baazaar
Jalebi (film)
FryDay
Tumbbad
Helicopter Eela
Namaste England
Andhadhun
Badhaai Ho
5 Weddings
Kaashi in Search of Ganga
Dassehra
The Journey of Karma
Jack and Dil
Mohalla Assi
Pihu
Bhaiaji Superhit
Rajma Chawal
Zero (2018 film)
Simmba
Tiger Zinda Hai
Golmaal Again
Judwaa 2
Ok Jaanu
Coffee with D
Kaabil
Raees (film)
Thugs of Hindostan
Hind Ka Napak Ko Jawab: MSG Lion Heart 2
Running Shaadi
The Ghazi Attack
Irada (2017 film)
Rangoon (2017 Hindi film)
Wedding Anniversary
Jeena Isi Ka Naam Hai (film)
Badrinath Ki Dulhania
Trapped (2016 Hindi film)
Aa Gaya Hero
Mantra (2016 film)
Phillauri (film)
Machine (2017 film)
Bhanwarey
Anaarkali of Aarah
Naam Shabana
Hotel Salvation
Begum Jaan
Noor (film)
Ek Thi Rani Aisi Bhi
Maatr
Sarkar 3
Jattu Engineer
Half Girlfriend (film)
Meri Pyaari Bindu
Sachin: A Billion Dreams
Hindi Medium
Sweetiee Weds NRI
Dobaara: See Your Evil
Flat 211
Dear Maya
Raabta (film)
Behen Hogi Teri
Tubelight (2017 Hindi film)
Bank Chor
Ek Haseena Thi Ek Deewana Tha
Jagga Jasoos
Shab (film)
Lipstick Under My Burkha
Bachche Kachche Sachche
G Kutta Se
Indu Sarkar
Jab Harry Met Sejal
Munna Michael
Toilet: Ek Prem Katha
Mubarakan
Guest iin London
Bareilly Ki Barfi
Babumoshai Bandookbaaz
Yadvi – The Dignified Princess
Qaidi Band
Shubh Mangal Saavdhan
Raag Desh (film)
Daddy (2017 film)
Simran (film)
Lucknow Central
A Gentleman
Viceroy's House (film)
Patel Ki Punjabi Shaadi
Newton (film)
The Final Exit
Bhoomi (film)
Haseena Parkar
JD (film)
Haraamkhor
Poster Boys
Mom (film)
Chef (2017 film)
Ranchi Diaries
Babuji Ek Ticket Bambai
Rukh (film)
Secret Superstar
Aval (2017 film)
Ribbon (film)
Shaadi Mein Zaroor Aana
Jia Aur Jia
Qarib Qarib Singlle
Aksar 2
Panchlait
Tumhari Sulu
Julie 2
Kadvi Hawa
Firangi
Fukrey Returns
Monsoon Shootout
Ajji
Chalk n Duster
Rebellious Flower
Saankal
Airlift (film)
Sallu Ki Shaadi
Irudhi Suttru
Kyaa Kool Hain Hum 3
Mastizaade
Dil Jo Na Keh Saka
Jugni (2016 film)
Ghayal: Once Again
Fitoor
Sanam Re
Direct Ishq
Ishq Forever
Loveshhuda
Neerja
Aligarh (film)
Bollywood Diaries
Love Shagun
Tere Bin Laden: Dead or Alive
Jai Gangaajal
Kapoor & Sons
Rocky Handsome
Love Games (film)
Fan (film)
Nil Battey Sannata
Laal Rang
Baaghi (2016 film)
Global Baba
Shortcut Safari
The Blueberry Hunt
Santa Banta Pvt Ltd
Traffic (2016 film)
1920: London
Azhar (film)
Buddha in a Traffic Jam
Murari the Mad Gentleman
Dear Dad (film)
Phobia (2016 film)
Sarbjit (film)
Veerappan (2016 film)
Do Lafzon Ki Kahani (film)
Te3n
Udta Punjab
Khel Toh Ab Shuru Hoga
Luv U Alia
7 Hours to Go
Raman Raghav 2.0
Junooniyat
Rough Book
Dhanak
Fredrick (film)
Dil Toh Deewana Hai
Sultan (2016 film)
Brahman Naman
Great Grand Masti
Waiting (2015 film)
Ishq Click
M Cream
Madaari
Dishoom
Fever (2016 film)
Rustom (film)
Hai Apna Dil Toh Awara
Mohenjo Daro (film)
Happy Bhag Jayegi
Waarrior Savitri
A Flying Jatt
Baar Baar Dekho
Freaky Ali
Raaz: Reboot
Pink (2016 film)
Parched
Banjo (2016 film)
Days of Tafree
Wah Taj
Island City (2015 film)
Ek Kahani Julie Ki
M.S. Dhoni: The Untold Story
MSG: The Warrior Lion Heart
Devi (2016 film)
Motu Patlu: King of Kings
Anna (2016 film)
Fuddu
Saat Uchakkey
Beiimaan Love
Umrika
Shivaay
Dongari Ka Raja
Ae Dil Hai Mushkil
Tum Bin II
Rock On 2
Force 2
Dear Zindagi
Befikre
Moh Maya Money
Shorgul
Saansein
Ki & Ka
Wajah Tum Ho
Dangal (film)
Mirzya (film)
Prem Ratan Dhan Payo
Tanu Weds Manu: Returns
Tanu Weds Manu: Returns
31st October (film)
ABCD 2
Dilwale (2015 film)
Bajrangi Bhaijaan
Bajirao Mastani
Welcome Back (film)
Baby (2015 Hindi film)
Singh Is Bliing
Gabbar Is Back
Gabbar Is Back
Mumbai Can Dance Saala
Alone (2015 Hindi film)
Tevar
Sharafat Gayi Tel Lene
Dolly Ki Doli
Hawaizaada
Khamoshiyan
Rahasya
Jai Jawaan Jai Kisaan (film)
Shamitabh
Roy (film)
Badlapur (film)
Crazy Cukkad Family
Take It Easy (2015 film)
Qissa (film)
Ab Tak Chhappan 2
Dum Laga Ke Haisha
Dirty Politics (film)
MSG: The Messenger
Badmashiyaan
Coffee Bloom
Hey Bro
NH10 (film)
Hunterrr
Detective Byomkesh Bakshy!
Luckhnowi Ishq
Court (film)
Margarita with a Straw
Ek Paheli Leela
Barkhaa
Mr. X (2015 film)
NH-8 Road to Nidhivan
Dilliwali Zaalim Girlfriend
Dharam Sankat Mein
Kaagaz Ke Fools
Kuch Kuch Locha Hai
Piku
Bombay Velvet
I Love Desi
Dil Dhadakne Do
Welcome 2 Karachi
P Se PM Tak
Mere Genie Uncle
Hamari Adhuri Kahani
Miss Tanakpur Haazir Ho
Uvaa
Ishq Ke Parindey
Ishqedarriyaan
Sabki Bajegi Band
Masaan
Guddu Rangeela
Bezubaan Ishq
Aisa Yeh Jahaan
Second Hand Husband
I Love NY (2015 film)
Main Hoon Part-Time Killer
Kaun Kitne Paani Mein
Drishyam (2015 film)
Bangistan
All Is Well (2015 film)
Brothers (2015 film)
Gour Hari Dastaan
Manjhi – The Mountain Man
Thoda Lutf Thoda Ishq
Phantom (2015 film)
Hero (2015 Hindi film)
Sorry Daddy
Talvar (film)
Katti Batti
Meeruthiya Gangsters
MSG-2 The Messenger
Calendar Girls (2015 film)
Bhaag Johnny
Jazbaa
Bumper Draw
Chinar Daastaan-E-Ishq
Kis Kisko Pyaar Karoon
Pyaar Ka Punchnama 2
Wedding Pullav
Shaandaar
Titli (2014 film)
Guddu Ki Gun
The Silent Heroes
Ranbanka
Sholay
Dedh Ishqiya
Karle Pyaar Karle
Om-Dar-B-Dar
Paranthe Wali Gali
Strings of Passion
Gunday
Jai Ho (film)
Hasee Toh Phasee
Heartless (2014 film)
Ya Rab
Darr @ the Mall
One by Two (2014 film)
Babloo Happy Hai
Highway (2014 Hindi film)
Gulabi Gang (film)
Shaadi Ke Side Effects
Gulaab Gang
Queen (2014 film)
Bewakoofiyaan
Total Siyapaa
Karar: The Deal
Lakshmi (2014 film)
Ragini MMS 2
Dishkiyaoon
Ankhon Dekhi
Gang of Ghosts
Anuradha (2014 film)
W (2014 film)
O Teri
Honour Killing (film)
2 States (2014 film)
Jal (film)
Bhoothnath Returns
Main Tera Hero
Lucky Kabootar
Station (2014 film)
Youngistaan
Samrat & Co.
Purani Jeans
Kya Dilli Kya Lahore
Koyelaanchal
Manjunath (film)
Dekh Tamasha Dekh
Mastram
The Xposé
Children of War (2014 film)
Hawaa Hawaai
Kahin Hai Mera Pyar
Kuku Mathur Ki Jhand Ho Gayi
Heropanti
CityLights (2014 film)
Filmistaan
Revolver Rani
Kaanchi: The Unbreakable
Machhli Jal Ki Rani Hai
Khwaabb
Yeh Hai Bakrapur
Ek Villain
Bobby Jasoos
Humshakals
Humpty Sharma Ki Dulhania
Hate Story 2
Lekar Hum Deewana Dil
Riyasat (film)
Amit Sahni Ki List
Holiday: A Soldier Is Never Off Duty
Fugly (film)
Bazaar E Husn
Pizza (2014 film)
Entertainment (2014 film)
Singham Returns
Mardaani
Raja Natwarlal
Mary Kom (film)
Creature 3D
Finding Fanny
Khoobsurat (2014 film)
3 A.M. (2014 film)
Kick (2014 film)
Mad About Dance
Mumbhai Connection
Life Is Beautiful (2014 film)
Desi Kattey
Haider (film)
Bang Bang!
Spark (2014 film)
Daawat-e-Ishq
Balwinder Singh Famous Ho Gaya
Jigariyaa
Tamanchey
Mumbai 125 KM
Meinu Ek Ladki Chaahiye
Chaarfutiya Chhokare
Sonali Cable
Happy New Year (2014 film)
Super Nani
Ekkees Toppon Ki Salaami
Rang Rasiya
The Shaukeens
Roar: Tigers of the Sundarbans
A Decent Arrangement
Gollu Aur Pappu
Titoo MBA
Kill Dil
Ungli
Happy Ending (film)
Zed Plus
Zid (2014 film)
Action Jackson (2014 film)
Bhopal: A Prayer for Rain
Mumbai Delhi Mumbai
Badlapur Boys
Main Aur Mr. Riight
Ugly (film)
PK (film)
Dehraadun Diary
Matru Ki Bijlee Ka Mandola
Sulemani Keeda
Inkaar (2013 film)
Gangoobai
Akaash Vani
Main Krishna Hoon
Race 2
Bandook
Listen... Amaya
Special 26
Murder 3
Zila Ghaziabad
Kai Po Che!
Bloody Isshq
Saare Jahaan Se Mehnga
3G (film)
Mere Dad Ki Maruti
Jolly LLB
Saheb Biwi Aur Gangster Returns
Mai (2013 film)
Vishwaroopam
Rangrezz
Aashiqui 2
Ek Thi Daayan
Himmatwala (2013 film)
Nautanki Saala!
Jayantabhai Ki Luv Story
Commando: A One Man Army
Bombay Talkies (film)
Go Goa Gone
Gippi
Aurangzeb (film)
Ishkq in Paris
Zindagi 50-50
Yeh Jawaani Hai Deewani
Fukrey
Chhota Bheem and the Throne of Bali
Raanjhanaa
Ankur Arora Murder Case
Shortcut Romeo
Ghanchakkar (film)
Hum Hai Raahi Car Ke
Policegiri
Bhaag Milkha Bhaag
Sixteen (2013 Indian film)
B.A. Pass
Enemmy
Issaq
Bajatey Raho
Luv U Soniyo
Nasha (film)
Chor Chor Super Chor
Calapor (film)
Love in Bombay
D-Day (2013 film)
Siddharth (2013 film)
Once Upon ay Time in Mumbai Dobaara!
Madras Cafe
Satyagraha (film)
Shuddh Desi Romance
Ramaiya Vastavaiya
Chennai Express
Grand Masti
John Day (film)
Horror Story (film)
Phata Poster Nikhla Hero
Ship of Theseus (film)
The Lunchbox
Baat Bann Gayi
Boss (2013 Hindi film)
Shahid (film)
Mickey Virus
Satya 2
Rajjo
Maazii
Sooper Se Ooper
Prague (2013 film)
Wake Up India
Super Model (film)
Gori Tere Pyaar Mein
What the Fish
Jackpot (2013 film)
Table No. 21
Bullett Raja
Dhoom 3
Chashme Baddoor (2013 film)
Lootera
War Chhod Na Yaar
Chaalis Chauraasi
Ghost (2012 film)
Sadda Adda
Singh Saab the Great
Goliyon Ki Raasleela Ram-Leela
Agneepath (2012 film)
Ek Main Aur Ekk Tu
Ekk Deewana Tha
?: A Question Mark
Jodi Breakers
Tere Naal Love Ho Gaya
Staying Alive (2012 film)
Paan Singh Tomar (film)
Kahaani
Zindagi Tere Naam
Agent Vinod (2012 film)
Blood Money (2012 film)
Bumboo
Valentine's Night
Married 2 America
Chaar Din Ki Chandni
Bittoo Boss
Vicky Donor
Hate Story
Tezz
Dangerous Ishhq
Ishaqzaade
Department (film)
Fatso!
Arjun: The Warrior Prince
Life Ki Toh Lag Gayi
Shanghai (2012 film)
Ferrari Ki Sawaari
Teri Meri Kahaani (film)
Mr. Bhatti on Chutti
Yeh Khula Aasmaan
Rakhtbeej
Gangs of Wasseypur
Gangs of Wasseypur – Part 2
Cocktail (2012 film)
Gattu
Kyaa Super Kool Hain Hum
Maximum (film)
Paanch Ghantey Mien Paanch Crore
Ek Tha Tiger
Challo Driver
Shirin Farhad Ki Toh Nikal Padi
Joker (2012 film)
Aalaap (film)
Mere Dost Picture Abhi Baki Hai
Krishna Aur Kans
From Sydney with Love
Jalpari: The Desert Mermaid
Barfi!
Heroine (2012 film)
Chal Pichchur Banate Hain
Kismat Love Paisa Dilli
Jeena Hai Toh Thok Daal
OMG – Oh My God!
Aiyyaa
Chittagong (film)
Bhoot Returns
Delhi Safari
Chakravyuh (2012 film)
Student of the Year
Ajab Gazabb Love
Rush (2012 film)
1920: The Evil Returns
Sons of Ram
Ata Pata Laapata
Jab Tak Hai Jaan
Talaash: The Answer Lies Within
Login (film)
Son of Sardaar
Cigarette Ki Tarah
Dabangg 2
Players (2012 film)
Housefull 2
Bol Bachchan
English Vinglish
Impatient Vivek
Yamla Pagla Deewana
Mumbai Mast Kallander
Dhobi Ghat (film)
Turning 30
Hostel (2011 film)
Dil Toh Baccha Hai Ji
United Six
Utt Pataang
Patiala House (film)
7 Khoon Maaf
Tanu Weds Manu
F.A.L.T.U
Memories in March
Thank You (2011 film)
Angel (2011 film)
Happy Husbands (2011 film)
Teen Thay Bhai
Dum Maaro Dum (film)
Shor in the City
Zokkomon
Chalo Dilli
Aashiqui.in
Satrangee Parachute
Monica (film)
I Am (2010 Indian film)
Naughty @ 40
Haunted – 3D
Love U...Mr. Kalakaar!
Ragini MMS
Stanley Ka Dabba
Shagird (2011 film)
404 (film)
Shaitan (film)
Pyaar Ka Punchnama
Bheja Fry 2
Always Kabhi Kabhi
Double Dhamaal
Bbuddah... Hoga Terra Baap
Delhi Belly (film)
Murder 2
Chillar Party
Zindagi Na Milegi Dobara
Dear Friend Hitler
I Am Kalam
Bin Bulaye Baraati
Kucch Luv Jaisaa
Singham
Khap (film)
Bubble Gum (film)
Shabri
Phhir
Aarakshan
Chatur Singh Two Star
Sahi Dhandhe Galat Bande
Bodyguard (2011 Hindi film)
Yeh Dooriyan
Not a Love Story (2011 film)
Hum Tum Shabana
Mummy Punjabi
Mere Brother Ki Dulhan
Mausam (2011 film)
U R My Jaan
Force (2011 film)
Saheb Biwi Aur Gangster
Tere Mere Phere
Breakaway (2011 film)
Chargesheet (film)
Love Breakups Zindagi
Mujhse Fraaandship Karoge
Aazaan
Ra.One
Rockstar (2011 film)
Miley Naa Miley Hum
Tell Me O Kkhuda
Damadamm!
Ladies vs Ricky Bahl
Desi Boyz
Game (2011 film)
No One Killed Jessica
Rascals (2011 film)
The Dirty Picture
Pyaar Impossible!
Chance Pe Dance
My Friend Pinto
Veer (2010 film)
Striker (2010 film)
Rann (film)
Ishqiya
Road to Sangam
Jo Hum Chahein
Click (2010 film)
Toh Baat Pakki!
My Name Is Khan
Teen Patti (film)
Karthik Calling Karthik
Don 2
Rokkk
Aakhari Decision
Right Yaaa Wrong
Sukhmani: Hope for Life
Thanks Maa
Na Ghar Ke Na Ghaat Ke
Trump Card (film)
Shaapit
Hum Tum Aur Ghost
Well Done Abba
Tum Milo Toh Sahi
Jaane Kahan Se Aayi Hai
Prem Kaa Game
Sadiyaan
The Japanese Wife
Paathshaala
Phoonk 2
Lahore (film)
Apartment (film)
City of Gold (2010 film)
Chase (2010 film)
Housefull (2010 film)
Mittal v/s Mittal
It's a Wonderful Afterlife
Prince (2010 film)
Raavan
Bumm Bumm Bole
Kushti (film)
Kites (film)
Love Sex Aur Dhokha
Milenge Milenge
Ek Second... Jo Zindagi Badal De?
Mr. Singh Mrs. Mehta
Lamhaa
Khatta Meetha (2010 film)
Tere Bin Laden
Udaan (2010 film)
Once Upon a Time in Mumbaai
Help (film)
Peepli Live
Lafangey Parindey
Hello Darling
Antardwand
Aashayein
Soch Lo
Dabangg
Khichdi: The Movie
Red Alert: The War Within
Life Express (2010 film)
The Film Emotional Atyachar
Hisss
Crook (film)
Do Dooni Chaar
Aakrosh (2010 film)
Ramayana: The Epic
Knock Out (2010 film)
Jhootha Hi Sahi
Guzaarish (film)
Allah Ke Banday
Break Ke Baad
Khuda Kasam
Phas Gaye Re Obama
Malik Ek
A Flat (film)
No Problem (2010 film)
Band Baaja Baaraat
Kaalo
Mirch
Tees Maar Khan (2010 film)
Isi Life Mein
Toonpur Ka Super Hero
Tera Kya Hoga Johnny
Ramaa: The Saviour
I Hate Luv Storys
Dulha Mil Gaya
Anjaana Anjaani
Dunno Y... Na Jaane Kyon
Pankh
Action Replayy
3 Idiots
Luck by Chance
Love Aaj Kal
Wanted (2009 film)
Delhi-6
Raaz: The Mystery Continues
Aasma: The Sky Is the Limit
Ajab Prem Ki Ghazab Kahani
Chal Chala Chal
Billu
The Stoneman Murders
Kisse Pyaar Karoon
Dhoondte Reh Jaaoge
Karma Aur Holi
Victory (2009 film)
Kaminey
Jai Veeru
Little Zizou
Gulaal (film)
Aloo Chaat (film)
Barah Aana
Firaaq
Aa Dekhen Zara
99 (2009 film)
Ek: The Power of One
Ek Se Bure Do
Sikandar (2009 film)
Zor Lagaa Ke...Haiya!
Paying Guests
New York (2009 film)
Sankat City
Shortkut
Luck (2009 film)
Life Partner
Daddy Cool (2009 Hindi film)
Kisaan
Yeh Mera India
Aagey Se Right
Chintu Ji
Quick Gun Murugun
Fox (film)
Baabarr
Phir Kabhi
Vaada Raha
Dil Bole Hadippa!
What's Your Raashee?
Acid Factory
All the Best: Fun Begins
Wake Up Sid
Main Aurr Mrs Khanna
Blue (2009 film)
Fruit and Nut (film)
Aladin (film)
London Dreams
Jail (2009 film)
Tum Mile
Kurbaan (2009 film)
De Dana Dan
Paa (film)
Rocket Singh: Salesman of the Year
Raat Gayi Baat Gayi?
Accident on Hill Road
Chandni Chowk to China
Dostana (2008 film)
Race (2008 film)
Rab Ne Bana Di Jodi
Ghajini (2008 film)
Singh Is Kinng
Golmaal Returns
Jodhaa Akbar
Bachna Ae Haseeno
Bhoothnath
Sarkar Raj
Halla Bol
Humne Jeena Seekh Liya
Bombay to Bangkok
Tulsi (film)
Sunday (2008 film)
One Two Three
Krazzy 4
U Me Aur Hum
Sirf (film)
Tashan (film)
Anamika (2008 film)
Jimmy (2008 film)
Jannat (film)
Don Muthu Swami
Woodstock Villa
Mere Baap Pehle Aap
Summer 2007
De Taali
Haal-e-Dil
Thodi Life Thoda Magic
Thoda Pyaar Thoda Magic
Via Darjeeling
Kismat Konnection
Love Story 2050
Contract (2008 film)
Mission Istaanbul
Money Hai Toh Honey Hai
God Tussi Great Ho
Mumbai Meri Jaan
Maan Gaye Mughal-e-Azam
Rock On!!
C Kkompany
Chamku
Mukhbiir
Tahaan
1920 (film)
The Last Lear
Welcome to Sajjanpur
Saas Bahu Aur Sensex
Hari Puttar: A Comedy of Terrors
Drona (2008 film)
Hello (2008 film)
Karzzzz
Heroes (2008 film)
Roadside Romeo
Ek Vivaah... Aisa Bhi
Deshdrohi
Fashion (2008 film)
Dasvidaniya
Yuvvraaj
Oye Lucky! Lucky Oye!
Oh My God (2008 film)
Sorry Bhai!
1971 (2007 film)
Meerabai Not Out
Wafa: A Deadly Love Story
Gumnaam – The Mystery
Dil Kabaddi
Aag (2007 film)
Aap Kaa Surroor
Aggar (film)
Anwar (2007 film)
Aaja Nachle
Apne
Awarapan
Bheja Fry (film)
Bhool Bhulaiyaa
Bhram
Big Brother (2007 film)
68 Pages
Aur Pappu Paas Ho Gaya
Apna Asmaan
Black Friday (2007 film)
The Blue Umbrella (2005 film)
Blood Brothers (2007 Indian film)
Buddha Mar Gaya
Cash (2007 film)
Cheeni Kum
Chhodon Naa Yaar
Darling (2007 Indian film)
Chak De! India
Dhamaal
Goal (2007 Hindi film)
Dharm (film)
Bombay to Goa (2007 film)
Dhokha
Dil Dosti Etc
Dhol (film)
Ek Chalis Ki Last Local
Familywala
Gandhi My Father
Don't Stop Dreaming
Dus Kahaniyaan
Eklavya: The Royal Guard
Go (2007 film)
Gauri: The Unborn
Heyy Babyy
Guru (2007 film)
Honeymoon Travels Pvt. Ltd.
Jahan Jaaeyega Hamen Paaeyega
Jhoom Barabar Jhoom
Jab We Met
Good Boy Bad Boy
Fool & Final
Khoya Khoya Chand
Johnny Gaddaar
Just Married (2007 film)
Kya Love Story Hai
Kudiyon Ka Hai Zamana
Hastey Hastey
Laaga Chunari Mein Daag
Life in a... Metro
Loins of Punjab Presents
Manorama Six Feet Under
Marigold (2007 film)
MP3: Mera Pehla Pehla Pyaar
Hattrick (film)
Naqaab
Mumbai Salsa
The Namesake (film)
Namastey London
My Bollywood Bride
Nehlle Pe Dehlla
Nishabd
No Smoking (2007 film)
Om Shanti Om
Partner (2007 film)
Raqeeb
Nanhe Jaisalmer
Life Mein Kabhie Kabhiee
Risk (2007 film)
Shakalaka Boom Boom
Red Swastik
Salaam-e-Ishq: A Tribute to Love
Saawariya
Sarhad Paar
Say Salaam India
Red: The Dark Side
Shootout at Lokhandwala
Strangers (2007 Hindi film)
Swami (2007 film)
Taare Zameen Par
Ta Ra Rum Pum
Speed (2007 film)
Traffic Signal (film)
The Train (2007 film)
Showbiz (film)
Sunglass (film)
Welcome (2007 film)
36 China Town
Zamaanat
Aap Ki Khatir (2006 film)
Ahista Ahista (2006 film)
Aksar
Alag
Anthony Kaun Hai?
Apna Sapna Money Money
Ankahee (2006 film)
Yatra (2007 film)
Baabul (2006 film)
Aisa Kyon Hota Hai?
Adharm (2006 film)
Being Cyrus
Banaras (2006 film)
Bas Ek Pal
Bhagam Bhag
Chingaari
Bhoot Unkle
Chand Ke Paar Chalo (film)
Aryan: Unbreakable
Chup Chup Ke
Corporate (2006 film)
Darna Zaroori Hai
Deadline: Sirf 24 Ghante
Dil Diya Hai
Darwaaza Bandh Rakho
Eight: The Power of Shani
Dhoom 2
Dor (film)
Don (2006 Hindi film)
Family (2006 film)
Fanaa (2006 film)
Gangster (2006 film)
Golmaal: Fun Unlimited
Devaki (2005 film)
Fight Club – Members Only
Dharti Kahe Pukar Ke (2006 film)
Humko Deewana Kar Gaye
Humko Tumse Pyaar Hai
I See You (2006 film)
Jaane Hoga Kya
Jaan-E-Mann
Jawani Diwani: A Youthful Joyride
Holiday (2006 film)
Iqraar by Chance
Khosla Ka Ghosla
Kabhi Alvida Naa Kehna
Love Ke Chakkar Mein
Lage Raho Munna Bhai
Kabul Express
Jigyaasa
Krrish
Malamaal Weekly
Omkara (2006 film)
Pyaar Ke Side Effects
Naksha
Phir Hera Pheri
Pyare Mohan
Mere Jeevan Saathi (2006 film)
Prateeksha
Sacred Evil – A True Story
Rang De Basanti
Shaadi Karke Phas Gaya Yaar
Sandwich (2006 film)
Shaadi Se Pehle
Saawan... The Love Season

In [131]:
# Arithmetic operators
print(ms)
print(100-ms)
print(100+ms)

Bio          87
English      85
Physics      50
Chemistry    67
1            85
Maths        92
Name: Scorecard, dtype: int64
Bio          13
English      15
Physics      50
Chemistry    33
1            15
Maths         8
Name: Scorecard, dtype: int64
Bio          187
English      185
Physics      150
Chemistry    167
1            185
Maths        192
Name: Scorecard, dtype: int64

In [138]:
# Relational operators
print(runs.head())
print(runs.head()>50)
print(runs[runs>50].head()) # Boolean Masking

match_no
1     98
2     23
3     98
4     98
5    100
Name: runs, dtype: int64
match_no
1     True
2    False
3     True
4     True
5     True
Name: runs, dtype: bool
match_no
1      98
3      98
4      98
5     100
34     58
Name: runs, dtype: int64

In [141]:
# Value counts
print(lead)
num = lead.value_counts() # Gives frequency of values

movie
Uri: The Surgical Strike                   Vicky Kaushal
Battalion 609                                Vicky Ahuja
The Accidental Prime Minister (film)         Anupam Kher
Why Cheat India                            Emraan Hashmi
Evening Shadows                         Mona Ambegaonkar
                                              ...
Hum Tumhare Hain Sanam                    Shah Rukh Khan
Aankhen (2002 film)                     Amitabh Bachchan
Saathiya (film)                             Vivek Oberoi
Company (film)                                Ajay Devgn
Awara Paagal Deewana                        Akshay Kumar
Name: lead, Length: 1500, dtype: str

In [144]:
# Boolean masking
print(num[num>20])
print(num[num>20].size)

lead
Akshay Kumar        48
Amitabh Bachchan    45
Ajay Devgn          38
Salman Khan         31
Sanjay Dutt         26
Shah Rukh Khan      22
Emraan Hashmi       21
Name: count, dtype: int64
7