### **Pandas Series**
Pandas Series and it's operations

---

Pandas used for :
- Data Analysis
- Data Manipulation

---
Pandas has 2 objects :
- Series
- Dataframe

Series: 1-D array of data of any type. Just like a column in a table

In [1]:
# Importing Pandas
import numpy as np
import pandas as pd

### Initializing Series

In [15]:
# List of Strings values
country = ['India', 'Pakistan', 'USA', 'Nepal', 'Bangladesh']
pd.Series(country)

0         India
1      Pakistan
2           USA
3         Nepal
4    Bangladesh
dtype: str

- As you can see here, series contains **Index** and **Values**

In [16]:
# List of  Numeric values
runs = np.random.randint(1,100,5)
pd.Series(runs)

0    48
1    70
2     6
3    78
4    20
dtype: int32

In [9]:
# Custom Index
marks = np.random.randint(50,100,4)
subjects = ['Maths', 'English', 'Physics', 'Chemistry']

pd.Series(marks, index=subjects)

Maths        87
English      91
Physics      50
Chemistry    67
dtype: int32

In [10]:
# Naming a series
pd.Series(marks, index=subjects, name='Scorecard')

Maths        87
English      91
Physics      50
Chemistry    67
Name: Scorecard, dtype: int32

In [12]:
# Initializing series from dict
marks = {
    'Bio':87,
    'English':91,
    'Physics':50,
    'Chemistry':67
}

pd.Series(marks)

Bio          87
English      91
Physics      50
Chemistry    67
dtype: int64

In [17]:
# List of different data types
li = ['Lakshya',40,29,'Akshat',48]
pd.Series(li)

0    Lakshya
1         40
2         29
3     Akshat
4         48
dtype: object

- Here, object dtype means **string values** and int values are treated as strings

### Series Attributes

In [34]:
ms = pd.Series(marks, name='Scorecard')
ms

Bio          87
English      91
Physics      50
Chemistry    67
Name: Scorecard, dtype: int64

In [30]:
# size
ms.size # Number of elements in series

4

In [32]:
# dtype
ms.dtype # Type of element

dtype('int64')

In [35]:
# name
ms.name # Name of series

'Scorecard'

In [37]:
# is_unique
ms.is_unique # Tells if every item is unique or not

True

In [38]:
pd.Series([1,1,1,3,5,6,8,2]).is_unique

False

In [40]:
# index
ms.index # Gives index values

Index(['Bio', 'English', 'Physics', 'Chemistry'], dtype='str')

In [41]:
pd.Series([1,1,1,3,5,6,8,2]).index

RangeIndex(start=0, stop=8, step=1)

In [43]:
# values
ms.values # Gives values of series

array([87, 91, 50, 67])

### Initializing series from dataset

In [70]:
print(type(pd.read_csv('Pandas_Dataset\\subs.csv')))
pd.read_csv('Pandas_Dataset\\subs.csv') # Returns Dataframe

<class 'pandas.DataFrame'>

     Subscribers gained
0                    48
1                    57
2                    40
3                    43
4                    44
..                  ...
360                 231
361                 226
362                 155
363                 144
364                 172

[365 rows x 1 columns]

In [54]:
print(type(pd.read_csv('Pandas_Dataset\\subs.csv').squeeze()))
pd.read_csv('Pandas_Dataset\\subs.csv').squeeze()

<class 'pandas.Series'>

0       48
1       57
2       40
3       43
4       44
      ...
360    231
361    226
362    155
363    144
364    172
Name: Subscribers gained, Length: 365, dtype: int64

- Returns series in single column dataset
- Column name is taken as name automatically by pandas

In [58]:
# dataset with 2 columns
pd.read_csv('Pandas_Dataset\\kohli_ipl.csv')

     match_no  runs
0           1     1
1           2    23
2           3    13
3           4    12
4           5     1
..        ...   ...
210       211     0
211       212    20
212       213    73
213       214    25
214       215     7

[215 rows x 2 columns]

In [57]:
pd.read_csv('Pandas_Dataset\\kohli_ipl.csv', index_col='match_no').squeeze()

match_no
1       1
2      23
3      13
4      12
5       1
       ..
211     0
212    20
213    73
214    25
215     7
Name: runs, Length: 215, dtype: int64

In [59]:
pd.read_csv('Pandas_Dataset\\bollywood.csv')

                                     movie              lead
0                 Uri: The Surgical Strike     Vicky Kaushal
1                            Battalion 609       Vicky Ahuja
2     The Accidental Prime Minister (film)       Anupam Kher
3                          Why Cheat India     Emraan Hashmi
4                          Evening Shadows  Mona Ambegaonkar
...                                    ...               ...
1495                Hum Tumhare Hain Sanam    Shah Rukh Khan
1496                   Aankhen (2002 film)  Amitabh Bachchan
1497                       Saathiya (film)      Vivek Oberoi
1498                        Company (film)        Ajay Devgn
1499                  Awara Paagal Deewana      Akshay Kumar

[1500 rows x 2 columns]

In [60]:
pd.read_csv('Pandas_Dataset\\bollywood.csv', index_col='movie').squeeze()

movie
Uri: The Surgical Strike                   Vicky Kaushal
Battalion 609                                Vicky Ahuja
The Accidental Prime Minister (film)         Anupam Kher
Why Cheat India                            Emraan Hashmi
Evening Shadows                         Mona Ambegaonkar
                                              ...
Hum Tumhare Hain Sanam                    Shah Rukh Khan
Aankhen (2002 film)                     Amitabh Bachchan
Saathiya (film)                             Vivek Oberoi
Company (film)                                Ajay Devgn
Awara Paagal Deewana                        Akshay Kumar
Name: lead, Length: 1500, dtype: str

### Series Basic Methods

In [71]:
subs = pd.read_csv('Pandas_Dataset\\subs.csv').squeeze()
runs = pd.read_csv('Pandas_Dataset\\kohli_ipl.csv', index_col='match_no').squeeze()
lead = pd.read_csv('Pandas_Dataset\\bollywood.csv', index_col='movie').squeeze()

In [82]:
# head
subs.head() # Gives top 5 rows by default

0    48
1    57
2    40
3    43
4    44
Name: Subscribers gained, dtype: int64

In [74]:
subs.head(8)

0    48
1    57
2    40
3    43
4    44
5    46
6    33
7    40
Name: Subscribers gained, dtype: int64

In [83]:
# tail
subs.tail() # Gives last 5 rows by default

360    231
361    226
362    155
363    144
364    172
Name: Subscribers gained, dtype: int64

In [77]:
subs.tail(3)

362    155
363    144
364    172
Name: Subscribers gained, dtype: int64

In [81]:
# Sample
lead.sample() # Randomly gives row

movie
Amit Sahni Ki List    Vir Das
Name: lead, dtype: str

In [80]:
lead.sample(3)

movie
Hind Ka Napak Ko Jawab: MSG Lion Heart 2    Gurmeet Ram Rahim Singh
Dil Bechara                                    Sushant Singh Rajput
Tees Maar Khan (2010 film)                             Akshay Kumar
Name: lead, dtype: str

In [84]:
# value_counts
lead

movie
Uri: The Surgical Strike                   Vicky Kaushal
Battalion 609                                Vicky Ahuja
The Accidental Prime Minister (film)         Anupam Kher
Why Cheat India                            Emraan Hashmi
Evening Shadows                         Mona Ambegaonkar
                                              ...
Hum Tumhare Hain Sanam                    Shah Rukh Khan
Aankhen (2002 film)                     Amitabh Bachchan
Saathiya (film)                             Vivek Oberoi
Company (film)                                Ajay Devgn
Awara Paagal Deewana                        Akshay Kumar
Name: lead, Length: 1500, dtype: str

In [86]:
lead.value_counts() # Gives frequency of series values

lead
Akshay Kumar        48
Amitabh Bachchan    45
Ajay Devgn          38
Salman Khan         31
Sanjay Dutt         26
                    ..
Tanishaa Mukerji     1
Tanuja               1
Ankit                1
Rakhee Gulzar        1
Edwin Fernandes      1
Name: count, Length: 566, dtype: int64

In [87]:
# sort_values
runs

match_no
1       1
2      23
3      13
4      12
5       1
       ..
211     0
212    20
213    73
214    25
215     7
Name: runs, Length: 215, dtype: int64

In [89]:
runs.sort_values() # Sort values of series in ascending order

match_no
8        0
87       0
93       0
91       0
206      0
      ...
164    100
120    100
123    108
126    109
128    113
Name: runs, Length: 215, dtype: int64

In [90]:
runs.sort_values(ascending=False) # Sort values of series in descending order

match_no
128    113
126    109
123    108
120    100
164    100
      ...
93       0
130      0
206      0
207      0
211      0
Name: runs, Length: 215, dtype: int64

In [97]:
runs.sort_values(ascending=False).values[0]

np.int64(113)

In [102]:
runs.sort_values(inplace=True) # Made changes to original series, by default it's false
runs

match_no
8        0
87       0
93       0
91       0
206      0
      ...
164    100
120    100
123    108
126    109
128    113
Name: runs, Length: 215, dtype: int64

In [99]:
# sort_index
lead

movie
Uri: The Surgical Strike                   Vicky Kaushal
Battalion 609                                Vicky Ahuja
The Accidental Prime Minister (film)         Anupam Kher
Why Cheat India                            Emraan Hashmi
Evening Shadows                         Mona Ambegaonkar
                                              ...
Hum Tumhare Hain Sanam                    Shah Rukh Khan
Aankhen (2002 film)                     Amitabh Bachchan
Saathiya (film)                             Vivek Oberoi
Company (film)                                Ajay Devgn
Awara Paagal Deewana                        Akshay Kumar
Name: lead, Length: 1500, dtype: str

In [101]:
lead.sort_index() # Sort index of series

movie
1920 (film)                   Rajniesh Duggall
1920: London                     Sharman Joshi
1920: The Evil Returns             Vicky Ahuja
1971 (2007 film)                Manoj Bajpayee
2 States (2014 film)              Arjun Kapoor
                                   ...
Zindagi 50-50                      Veena Malik
Zindagi Na Milegi Dobara        Hrithik Roshan
Zindagi Tere Naam           Mithun Chakraborty
Zokkomon                       Darsheel Safary
Zor Lagaa Ke...Haiya!            Meghan Jadhav
Name: lead, Length: 1500, dtype: str