### **Plotly**
Data Visualization Library

**Advantages:**
- Multi language support (Python, JS, Julia)
- Lot's of graphs
- Interactive plots
- Beautiful plots

**Three main components:**
- Graph Objects (go)
- Plotly Express
- Dash

In [1]:
import plotly.graph_objects as go
import plotly.express as px
import numpy as np
import pandas as pd

### Working with Plotly go

In [2]:
# importing dataset
tips = px.data.tips()
iris = px.data.iris()
gap = px.data.gapminder()

In [3]:
tips.head()

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [4]:
iris.head()

   sepal_length  sepal_width  petal_length  petal_width species  species_id
0           5.1          3.5           1.4          0.2  setosa           1
1           4.9          3.0           1.4          0.2  setosa           1
2           4.7          3.2           1.3          0.2  setosa           1
3           4.6          3.1           1.5          0.2  setosa           1
4           5.0          3.6           1.4          0.2  setosa           1

In [5]:
gap.head()

,country,continent,year,lifeExp,pop,gdpPercap,iso_alpha,iso_num
0,Afghanistan,Asia,1952,28.801,8425333,779.445314,AFG,4
1,Afghanistan,Asia,1957,30.332,9240934,820.853030,AFG,4
2,Afghanistan,Asia,1962,31.997,10267083,853.100710,AFG,4
3,Afghanistan,Asia,1967,34.020,11537966,836.197138,AFG,4
4,Afghanistan,Asia,1972,36.088,13079460,739.981106,AFG,4

- Scatter plot ->

In [6]:
# scatter plot using plotly go
df = gap[gap['year'] == 2007]
df.head()

,country,continent,year,lifeExp,pop,gdpPercap,iso_alpha,iso_num
11,Afghanistan,Asia,2007,43.828,31889923,974.580338,AFG,4
23,Albania,Europe,2007,76.423,3600523,5937.029526,ALB,8
35,Algeria,Africa,2007,72.301,33333216,6223.367465,DZA,12
47,Angola,Africa,2007,42.731,12420476,4797.231267,AGO,24
59,Argentina,Americas,2007,75.320,40301927,12779.379640,ARG,32

In [7]:
trace1 = go.Scatter(x=df['lifeExp'], y=df['gdpPercap'], mode='markers')
trace2 = go.Scatter(x=[0,10,40], y=[0,9000,30000], mode='lines')
layout = go.Layout(title='Life Exp Vs GDP per Capita for 2007', xaxis={'title':'Life Exp', 'color':'aqua'}, yaxis={'title':'GDP'})

data = [trace1, trace2]

fig = go.Figure(data, layout)
fig.show()

In [8]:
# scatter plot using plotly express
px.scatter(df, x='lifeExp', y='gdpPercap', color='continent', size='pop', size_max=50, hover_name='country')

In [9]:
# plotting animation
px.scatter(gap, x='lifeExp', y='gdpPercap', color='continent', size='pop',
            size_max=50, hover_name='country', animation_frame='year',
            animation_group='country', range_x=[30,90], range_y=[-10000,51000])

- Line plot ->

In [10]:
gap.head()

,country,continent,year,lifeExp,pop,gdpPercap,iso_alpha,iso_num
0,Afghanistan,Asia,1952,28.801,8425333,779.445314,AFG,4
1,Afghanistan,Asia,1957,30.332,9240934,820.853030,AFG,4
2,Afghanistan,Asia,1962,31.997,10267083,853.100710,AFG,4
3,Afghanistan,Asia,1967,34.020,11537966,836.197138,AFG,4
4,Afghanistan,Asia,1972,36.088,13079460,739.981106,AFG,4

In [11]:
df = gap[gap['country'] == 'India']
df.head()

    country continent  year  lifeExp        pop   gdpPercap iso_alpha  iso_num
696   India      Asia  1952   37.373  372000000  546.565749       IND      356
697   India      Asia  1957   40.249  409000000  590.061996       IND      356
698   India      Asia  1962   43.605  454000000  658.347151       IND      356
699   India      Asia  1967   47.193  506000000  700.770611       IND      356
700   India      Asia  1972   50.651  567000000  724.032527       IND      356

In [12]:
px.line(df, x='year', y='pop', title='India pop Growth')

In [13]:
# plot india china pakistan line plot
df = gap[gap['country'].isin(['India', 'China', 'Pakistan'])].pivot(index='year', columns='country',values='lifeExp')
df.head()

country     China   India  Pakistan
year
1952     44.00000  37.373    43.436
1957     50.54896  40.249    45.557
1962     44.50136  43.605    47.670
1967     58.38112  47.193    49.800
1972     63.11888  50.651    51.929

In [14]:
px.line(df, x=df.index,y=df.columns)

- Bar chart ->

In [15]:
# india's pop over the year
df = gap[gap['country'] == 'India']
df.head()

    country continent  year  lifeExp        pop   gdpPercap iso_alpha  iso_num
696   India      Asia  1952   37.373  372000000  546.565749       IND      356
697   India      Asia  1957   40.249  409000000  590.061996       IND      356
698   India      Asia  1962   43.605  454000000  658.347151       IND      356
699   India      Asia  1967   47.193  506000000  700.770611       IND      356
700   India      Asia  1972   50.651  567000000  724.032527       IND      356

In [16]:
px.bar(df, x='year', y='pop')

In [17]:
# pop comp of 3 coutries
df = gap[gap['country'].isin(['India', 'China', 'Pakistan'])].pivot(index='year', columns='country',values='gdpPercap')
df.head()

country       China       India     Pakistan
year
1952     400.448611  546.565749   684.597144
1957     575.987001  590.061996   747.083529
1962     487.674018  658.347151   803.342742
1967     612.705693  700.770611   942.408259
1972     676.900092  724.032527  1049.938981

In [18]:
px.bar(df, x=df.index, y=df.columns, barmode='group')

In [19]:
df = gap[gap['country'].isin(['India', 'China', 'Pakistan'])].pivot(index='year', columns='country',values='pop')
df.head()

country      China      India  Pakistan
year
1952     556263527  372000000  41346560
1957     637408000  409000000  46679944
1962     665770000  454000000  53100671
1967     754550000  506000000  60641899
1972     862030000  567000000  69325921

In [20]:
px.bar(df, x=df.index, y=df.columns, barmode='group', log_y=True, text_auto=True)

In [21]:
# stacked bar chart
# pop contribution per country to a continents pop stacked for a particular year(2007)

df = gap[gap['year'] == 2007]
df.head()

,country,continent,year,lifeExp,pop,gdpPercap,iso_alpha,iso_num
11,Afghanistan,Asia,2007,43.828,31889923,974.580338,AFG,4
23,Albania,Europe,2007,76.423,3600523,5937.029526,ALB,8
35,Algeria,Africa,2007,72.301,33333216,6223.367465,DZA,12
47,Angola,Africa,2007,42.731,12420476,4797.231267,AGO,24
59,Argentina,Americas,2007,75.320,40301927,12779.379640,ARG,32

In [22]:
px.bar(df, x='continent', y='pop', color='country', log_y=True)

In [23]:
# bar chart animation
gap.head()

,country,continent,year,lifeExp,pop,gdpPercap,iso_alpha,iso_num
0,Afghanistan,Asia,1952,28.801,8425333,779.445314,AFG,4
1,Afghanistan,Asia,1957,30.332,9240934,820.853030,AFG,4
2,Afghanistan,Asia,1962,31.997,10267083,853.100710,AFG,4
3,Afghanistan,Asia,1967,34.020,11537966,836.197138,AFG,4
4,Afghanistan,Asia,1972,36.088,13079460,739.981106,AFG,4

In [24]:
px.bar(gap, x='continent', y='pop', color='country', animation_frame='year', animation_group='country', range_y=[0,4000000000])

- Histogram ->

In [25]:
# plot histogram of life exp of all countries in 2007
df = gap[gap['year'] == 2007]
df.head()

,country,continent,year,lifeExp,pop,gdpPercap,iso_alpha,iso_num
11,Afghanistan,Asia,2007,43.828,31889923,974.580338,AFG,4
23,Albania,Europe,2007,76.423,3600523,5937.029526,ALB,8
35,Algeria,Africa,2007,72.301,33333216,6223.367465,DZA,12
47,Angola,Africa,2007,42.731,12420476,4797.231267,AGO,24
59,Argentina,Americas,2007,75.320,40301927,12779.379640,ARG,32

In [26]:
px.histogram(df, x='lifeExp', nbins=50, text_auto=True)

In [27]:
# plot histogram of sepal length of all iris species
iris.head()

   sepal_length  sepal_width  petal_length  petal_width species  species_id
0           5.1          3.5           1.4          0.2  setosa           1
1           4.9          3.0           1.4          0.2  setosa           1
2           4.7          3.2           1.3          0.2  setosa           1
3           4.6          3.1           1.5          0.2  setosa           1
4           5.0          3.6           1.4          0.2  setosa           1

In [28]:
px.histogram(iris, x='sepal_length', color='species', text_auto=True)

- Pie chart ->

In [29]:
# find the pie chart of pop of european countries in 2007
df = gap[(gap['year'] == 2007) & (gap['continent'] == 'Europe')]
df.head()

,country,continent,year,lifeExp,pop,gdpPercap,iso_alpha,iso_num
23,Albania,Europe,2007,76.423,3600523,5937.029526,ALB,8
83,Austria,Europe,2007,79.829,8199783,36126.492700,AUT,40
119,Belgium,Europe,2007,79.441,10392226,33692.605080,BEL,56
155,Bosnia and Herzegovina,Europe,2007,74.852,4552198,7446.298803,BIH,70
191,Bulgaria,Europe,2007,73.005,7322858,10680.792820,BGR,100

In [30]:
px.pie(df, values='pop', names='country')

- Sunburst plot ->

In [31]:
df = gap[gap['year'] == 2007]
df.head()

,country,continent,year,lifeExp,pop,gdpPercap,iso_alpha,iso_num
11,Afghanistan,Asia,2007,43.828,31889923,974.580338,AFG,4
23,Albania,Europe,2007,76.423,3600523,5937.029526,ALB,8
35,Algeria,Africa,2007,72.301,33333216,6223.367465,DZA,12
47,Angola,Africa,2007,42.731,12420476,4797.231267,AGO,24
59,Argentina,Americas,2007,75.320,40301927,12779.379640,ARG,32

In [32]:
px.sunburst(df, path=['continent', 'country'], values='pop', color='lifeExp')

In [33]:
px.sunburst(tips, path=['sex','smoker','day','time'], values='total_bill', color='size')

- Treemap ->

In [34]:
df = gap[gap['year'] == 2007]
df.head()

,country,continent,year,lifeExp,pop,gdpPercap,iso_alpha,iso_num
11,Afghanistan,Asia,2007,43.828,31889923,974.580338,AFG,4
23,Albania,Europe,2007,76.423,3600523,5937.029526,ALB,8
35,Algeria,Africa,2007,72.301,33333216,6223.367465,DZA,12
47,Angola,Africa,2007,42.731,12420476,4797.231267,AGO,24
59,Argentina,Americas,2007,75.320,40301927,12779.379640,ARG,32

In [35]:
px.treemap(df, path=[px.Constant('World'),'continent', 'country'], values='pop', color='lifeExp')

- Heatmap ->

In [36]:
df = tips.pivot_table(index='day', columns='sex', values='total_bill', aggfunc='sum')
px.imshow(df)

- 3D plots ->

In [37]:
# scatter plot
df = gap[gap['year'] == 2007]
df.head()

,country,continent,year,lifeExp,pop,gdpPercap,iso_alpha,iso_num
11,Afghanistan,Asia,2007,43.828,31889923,974.580338,AFG,4
23,Albania,Europe,2007,76.423,3600523,5937.029526,ALB,8
35,Algeria,Africa,2007,72.301,33333216,6223.367465,DZA,12
47,Angola,Africa,2007,42.731,12420476,4797.231267,AGO,24
59,Argentina,Americas,2007,75.320,40301927,12779.379640,ARG,32

In [38]:
px.scatter_3d(df, x='lifeExp', y='pop', z='gdpPercap', log_y=True)

In [57]:
# surface plot
# cannot be created using plotly express but by graph objects
x = np.linspace(-10,10,100)
y = np.linspace(-10,10,100)

xx, yy = np.meshgrid(x,y)
z = xx**2 + yy**2

trace1 = go.Surface(x=x, y=y, z=z)
data = [trace1]
layout = go.Layout(title='3D Surface Plot')

fig = go.Figure(data, layout)
fig.show()

In [62]:
x = np.linspace(-10,10,100)
y = np.linspace(-10,10,100)

xx, yy = np.meshgrid(x,y)
z = np.sin(xx) + np.cos(yy)

trace1 = go.Surface(x=x, y=y, z=z)
data = [trace1]
layout = go.Layout(title='3D Surface Plot')

fig = go.Figure(data, layout)
fig.show()

- Contour plot ->

In [ ]:
x = np.linspace(-10,10,100)
y = np.linspace(-10,10,100)

xx, yy = np.meshgrid(x,y)
z = xx**2 + yy**2

trace1 = go.Contour(x=x, y=y, z=z)
data = [trace1]
layout = go.Layout(title='Contour Plot')

fig = go.Figure(data, layout)
fig.show()

- Scatter Matrix ->

In [ ]:
px.scatter_matrix(iris, dimensions=['sepal_length','sepal_width','petal_length','petal_width'], color='species')

- Facet plot ->

In [ ]:
tips.head()

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [55]:
px.scatter(tips, x='total_bill', y='tip', facet_col='day', facet_row='sex')